<a href="https://colab.research.google.com/github/maryamstraykid/fake-news-nlp-bibliometric-dataset-2017-2025/blob/main/Articles_data_cleaning_and_merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#citations

In [ ]:
pip install scholarly pandas

Collecting scholarly
  Downloading scholarly-1.7.11-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Collecting arrow (from scholarly)
  Downloading arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from scholarly) (4.13.4)
Collecting bibtexparser (from scholarly)
  Downloading bibtexparser-1.4.3.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: deprecated in /usr/local/lib/python3.11/dist-packages (from scholarly) (1.2.18)
Collecting fake-useragent (from scholarly)
  Downloading fake_useragent-2.2.0-py3-none-any.whl.metadata (17 kB)
Collecting free-proxy (from scholarly)
  Downloading free_proxy-1.1.3.tar.gz (5.6 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from scholarly) (0.28.1)
Collecting python-dotenv (from scholarly)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from scholarly) (2.32.3)
Collecting selenium (from scholarly)
  Downloading selenium-4.31.0-py3-none-any.whl.metadata (7.5 kB)
Collecting sphinx-rtd-theme (from scholarly)
  Downloading sphinx_rtd_theme-3.0.2-py2.py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from scholarly) (4.13.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting types-python-dateutil>=2.8.10 (from arrow->scholarly)
  Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->scholarly) (2.6)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from bibtexparser->scholarly) (3.2.3)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from deprecated->scholarly) (1.17.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from free-proxy->scholarly) (5.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->scholarly) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->scholarly) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->scholarly) (1.0.8)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->scholarly) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->scholarly) (0.14.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->scholarly) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->scholarly) (2.3.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->scholarly) (1.7.1)
Collecting trio~=0.17 (from selenium->scholarly)
  Downloading trio-0.30.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium->scholarly)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: websocket-client~=1.8 in /usr/local/lib/python3.11/dist-packages (from selenium->scholarly) (1.8.0)
Requirement already satisfied: sphinx<9,>=6 in /usr/local/lib/python3.11/dist-packages (from sphinx-rtd-theme->scholarly) (8.2.3)
Requirement already satisfied: docutils<0.22,>0.18 in /usr/local/lib/python3.11/dist-packages (from sphinx-rtd-theme->scholarly) (0.21.2)
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx-rtd-theme->scholarly)
  Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.18.0)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.2.0)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (1.4.1)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (3.1.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.11/dist-packages (from sphinx<9,>=6->sphinx-rtd-theme->scholarly) (24.2)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->scholarly) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->scholarly) (2.4.0)
Collecting outcome (from trio~=0.17->selenium->scholarly)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->scholarly) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium->scholarly)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=3.1->sphinx<9,>=6->sphinx-rtd-theme->scholarly) (3.0.2)
Downloading scholarly-1.7.11-py3-none-any.whl (39 kB)
Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.4 MB/s eta 0:00:00
Downloading fake_useragent-2.2.0-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.7/161.7 kB 6.6 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading selenium-4.31.0-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 78.2 MB/s eta 0:00:00
Downloading sphinx_rtd_theme-3.0.2-py2.py3-none-any.whl (7.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 69.3 MB/s eta 0:00:00
Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 8.1 MB/s eta 0:00:00
Downloading trio-0.30.0-py3-none-any.whl (499 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.2/499.2 kB 24.5 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl (14 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: bibtexparser, free-proxy
  Building wheel for bibtexparser (setup.py) ... done
  Created wheel for bibtexparser: filename=bibtexparser-1.4.3-py3-none-any.whl size=43549 sha256=9644e2c54d9e8a79fbf8f3cc30f8a831fd5580824e80325912261f21b2b89ad5
  Stored in directory: /root/.cache/pip/wheels/16/fb/76/306387739cf9d53b1c39b0c8aadbbb17dc05f256756d8fd915
  Building wheel for free-proxy (setup.py) ... done
  Created wheel for free-proxy: filename=free_proxy-1.1.3-py3-none-any.whl size=6097 sha256=a6324771a3598d6cbda9606184cc00437a53e87fbb165e1d88e46142e5a1322a
  Stored in directory: /root/.cache/pip/wheels/9e/f8/90/1e74c4166b7fbb213260a35e83fac3119f5e390c8bddda8a37
Successfully built bibtexparser free-proxy
Installing collected packages: wsproto, types-python-dateutil, python-dotenv, outcome, fake-useragent, bibtexparser, trio, free-proxy, arrow, trio-websocket, sphinxcontrib-jquery, sphinx-rtd-theme, selenium, scholarly
Successfully installed arrow-1.3.0 bibtexparser-1.4.3 fake-useragent-2.2.0 free-proxy-1.1.3 outcome-1.3.0.post0 python-dotenv-1.1.0 scholarly-1.7.11 selenium-4.31.0 sphinx-rtd-theme-3.0.2 sphinxcontrib-jquery-4.1 trio-0.30.0 trio-websocket-0.12.2 types-python-dateutil-2.9.0.20241206 wsproto-1.2.0

In [ ]:
import pandas as pd
from google.colab import files

# Upload CSV files
uploaded = files.upload()

Saving analyse bibliol ieee.csv to analyse bibliol ieee.csv

In [ ]:
# Load article titles from CSV (Exported from Zotero)
df = pd.read_csv("analyse bibliol ieee.csv")  # Make sure this file has a "Title" column

In [ ]:
df

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
0,H6LVW46C,conferencePaper,2024.0,"Vadakkethil Somanathan Pillai, Sanjaikanth E; ...",Leveraging Natural Language Processing for Det...,2024 2nd International Conference on Disruptiv...,NaN,NaN,10.1109/ICDT61202.2024.10489386,https://ieeexplore.ieee.org/document/10489386/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QFSGAUXJ,conferencePaper,2022.0,"Matheven, Anand; Kumar, Burra Venkata Durga",Fake News Detection Using Deep Learning and Na...,2022 9th International Conference on Soft Comp...,NaN,NaN,10.1109/ISCMI56532.2022.10068440,https://ieeexplore.ieee.org/document/10068440/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8RC5I9RH,conferencePaper,2024.0,"Nirmala, M; Navya, R",Machine Learning Techniques to Detect A Fake N...,2024 Second International Conference on Networ...,NaN,NaN,10.1109/NMITCON62075.2024.10699063,https://ieeexplore.ieee.org/document/10699063/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IUU7DPFA,conferencePaper,2023.0,"Misra, Shamik; Tandon, Prabhat; Panda, Purna C...",Optimization of Hugging Face Transformers for ...,"2023 International Conference on Data Science,...",NaN,NaN,10.1109/ICDSAAI59313.2023.10452606,https://ieeexplore.ieee.org/document/10452606/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3PDRPNI8,conferencePaper,2023.0,"Rakib Mollah, Md. Abdur; Kabir, Mir Md. Jahang...",Detection of Fake News with RoBERTa Based Embe...,2023 26th International Conference on Computer...,NaN,NaN,10.1109/ICCIT60459.2023.10441206,https://ieeexplore.ieee.org/document/10441206/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,7TMQ58DZ,conferencePaper,2023.0,"Misini, Arta; Kadriu, Arbana; Canhasi, Ercan",Albanian Authorship Attribution Model,2023 12th Mediterranean Conference on Embedded...,NaN,NaN,10.1109/MECO58584.2023.10155046,https://ieeexplore.ieee.org/document/10155046/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,E9BY98BZ,journalArticle,2020.0,"Kausar, Soufia; Tahir, Bilal; Mehmood, Muhamma...",ProSOUL: A Framework to Identify Propaganda Fr...,IEEE Access,NaN,2169-3536,10.1109/ACCESS.2020.3028131,https://ieeexplore.ieee.org/document/9210545/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,7AVYRDYK,conferencePaper,2023.0,"Pal, Satinder; Lamba, Anil Kumar",Tweeting Truth: Investigating False Informatio...,2023 IEEE World Conference on Applied Intellig...,NaN,NaN,10.1109/AIC57670.2023.10263951,https://ieeexplore.ieee.org/document/10263951/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,KFRUP6E2,conferencePaper,2024.0,"Chauhan, Shubham; Verma, Shija; Pandey, Ayushi...",Media Bias Monitor: Quantifying Biases of Indi...,2024 15th International Conference on Computin...,NaN,NaN,10.1109/ICCCNT61001.2024.10724364,https://ieeexplore.ieee.org/document/10724364/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,2AHV8G2Z,webpage,NaN,NaN,IEEE Xplore Search Results,NaN,NaN,NaN,NaN,https://ieeexplore.ieee.org/search/searchresul...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

citation_counts = []

# Search each article on Google Scholar
for title in df["Title"]:
    try:
        search_query = scholarly.search_pubs(title)  # Search article
        first_result = next(search_query)  # Get first match
        citations = first_result.get("num_citations", 0)  # Extract citation count
        citation_counts.append(citations)
        print(f"Fetched citations for {title}: {citations}")
    except Exception as e:
        citation_counts.append(None)
        print(f"Error fetching {title}: {e}")

# Add citations to the dataframe
df["Citations"] = citation_counts

# Save to a new CSV file
df.to_csv("articles_with_citations.csv", index=False)

print("Citation data saved successfully!")

Error fetching Leveraging Natural Language Processing for Detecting Fake News: A Comparative Analysis: name 'scholarly' is not defined
Error fetching Fake News Detection Using Deep Learning and Natural Language Processing: name 'scholarly' is not defined
Error fetching Machine Learning Techniques to Detect A Fake News In An Articles: name 'scholarly' is not defined
Error fetching Optimization of Hugging Face Transformers for Fake News Detection: name 'scholarly' is not defined
Error fetching Detection of Fake News with RoBERTa Based Embedding and Modified Deep Neural Network Architecture: name 'scholarly' is not defined
Error fetching Machine Learning for Fake News Detection on Social Media Text: name 'scholarly' is not defined
Error fetching A Comparison of Text Classification Methods: Towards Fake News Detection for Indonesian Websites: name 'scholarly' is not defined
Error fetching RealCheck: A Web Application for Fake News Detection Using Natural Language Processing: name 'scholarly' is not defined
Error fetching Fake News Detection Using Neural Network: name 'scholarly' is not defined
Error fetching Comparative Analysis Of Machine Learning Models For Fake News Classification: name 'scholarly' is not defined
Error fetching Fake News Detection Using Optimized Deep Learning Model Through Effective Feature Extraction: name 'scholarly' is not defined
Error fetching Boosting Fake News Detection Accuracy: A Deep Dive into LSTM Classifiers: name 'scholarly' is not defined
Error fetching Comparative Analysis of Learning Models for Solving Natural Language Processing Tasks: name 'scholarly' is not defined
Error fetching A Comprehensive Survey on Automatic Detection of Fake News Using Natural Language Processing: Challenges and Limitations: name 'scholarly' is not defined
Error fetching COVID-19 Fake News and Misinformation Detection using Transformer Learning: name 'scholarly' is not defined
Error fetching Unveiling Fake News with Machine Learning and Natural Language Processing Techniques: name 'scholarly' is not defined
Error fetching Fake News Detection using Machine Learning: name 'scholarly' is not defined
Error fetching Advancements in Fake News Detection: Integrating NLP and Multi-Modal Approaches: name 'scholarly' is not defined
Error fetching Active Learning for Text Classification and Fake News Detection: name 'scholarly' is not defined
Error fetching NLP-driven Content Classification Towards Fake News and Bully Detection: name 'scholarly' is not defined
Error fetching Systematic Literature Review on Methods used in Classification and Fake News Detection in Indonesian: name 'scholarly' is not defined
Error fetching Memory Based Online Fake News Detection System: name 'scholarly' is not defined
Error fetching Fake News Detection using Hybrid BiLSTM-TCN Model with Attention Mechanism: name 'scholarly' is not defined
Error fetching Cyber Sleuth: Harnessing NLP and Blockchain for Twitter Based Fake News Detection: name 'scholarly' is not defined
Error fetching News Category Classification using Natural Language Processing Transformer: name 'scholarly' is not defined
Error fetching A Natural Language Processing System for Truth Detection and Text Summarization: name 'scholarly' is not defined
Error fetching Fake news detection in Slovak language using deep learning techniques: name 'scholarly' is not defined
Error fetching Artificial Intelligence based Fake News Classification System: name 'scholarly' is not defined
Error fetching Identifying Inaccurate Stories: Leveraging High Knowledge and Big Data: name 'scholarly' is not defined
Error fetching A Brazilian Portuguese Moral Foundations Dictionary for Fake News classification: name 'scholarly' is not defined
Error fetching Natural Language Processing Approach for Fake News Detection Using Metaheuristics Optimized Extreme Gradient Boosting: name 'scholarly' is not defined
Error fetching Classifying Fake News Detection Using SVM, Naive Bayes and LSTM: name 'scholarly' is not defined
Error fetching Simultaneous Fake News and Topic Classification via Auxiliary Task Learning: name 'scholarly' is not defined
Error fetching An In-depth Analysis of Transformer Models for Enhanced Performance in Fake News Detection: name 'scholarly' is not defined
Error fetching The Use of Data Augmentation as a Technique for Improving Fake News Detection in the Romanian Language: name 'scholarly' is not defined
Error fetching Characterization, Classification and Detection of Fake News in Online Social Media Networks: name 'scholarly' is not defined
Error fetching Compact BERT-Based Multi-Models for Efficient Fake News Detection: name 'scholarly' is not defined
Error fetching Fake News Detection by Using Doc2Vec Representation Model and Various Classification Algorithms: name 'scholarly' is not defined
Error fetching Enhanced Detection of Misinformation Text-Based Fake News Analysis: name 'scholarly' is not defined
Error fetching Fake News Detection using Voting Ensemble Classifier: name 'scholarly' is not defined
Error fetching An Enhanced Fake News Detection System With Fuzzy Deep Learning: name 'scholarly' is not defined
Error fetching Fake News Detection Using Machine Learning Models: name 'scholarly' is not defined
Error fetching Data Augmentation for Fake News Using ChatGPT: name 'scholarly' is not defined
Error fetching Deep Learning-based Text News Classification using Bi-directional LSTM Model: name 'scholarly' is not defined
Error fetching Bangla Fake News Detection using Machine Learning, Deep Learning and Transformer Models: name 'scholarly' is not defined
Error fetching NEWSIFY: - Article Summarization using Natural Language Processing and News Authentication using TF-IDF Vectorizer and Passive Aggressive Classifier: name 'scholarly' is not defined
Error fetching Fake News Recognition: A Machine Learning Approach for Text Analysis using Hyperparameter Tuning: name 'scholarly' is not defined
Error fetching Fake News Detection Using Sentiment Analysis Approach in Indonesian Language: name 'scholarly' is not defined
Error fetching Performance Evaluation of Fake News Detection using Predictive Modeling: name 'scholarly' is not defined
Error fetching Utilizing Word Embedding and Linguistic Features for Fake News Detection: name 'scholarly' is not defined
Error fetching Smart Edge-based Fake News Detection using Pre-trained BERT Model: name 'scholarly' is not defined
Error fetching Optimizing Text Classification: A Comparative Analysis of Pre-Trained Models and Custom Neural Network Architectures on the AuTextification Dataset: name 'scholarly' is not defined
Error fetching Multilingual Misinformation Detection: Deep Learning Approaches for News Authenticity Assessment: name 'scholarly' is not defined
Error fetching A Novel Framework for Fake News Detection Using LDA and QDA: name 'scholarly' is not defined
Error fetching Easy Data Augmentation for Handling Imbalanced Data in Fake News Detection: name 'scholarly' is not defined
Error fetching Performance Analysis of ML Techniques in Identification of Fake News: name 'scholarly' is not defined
Error fetching A Hierarchical Framework for Fake News Detection Using Semantic Analysis and Source Reliability: name 'scholarly' is not defined
Error fetching Advancing Media Integrity through AI-Powered Fake News Detection: name 'scholarly' is not defined
Error fetching An Efficient Deep Learning Technique for Bangla Fake News Detection: name 'scholarly' is not defined
Error fetching Exploring Hierarchical Language Knowledge in Graph Neural Networks for Fake News Detection: name 'scholarly' is not defined
Error fetching A Study on Artificial Intelligence Techniques for Fake News Detection: name 'scholarly' is not defined
Error fetching Comparative Study of Classification Algorithms on Contrived News: name 'scholarly' is not defined
Error fetching Multi Class Fake News Detection using LSTM Approach: name 'scholarly' is not defined
Error fetching Fake News Detection Approach Using Hybrid Deep Learning Framework: name 'scholarly' is not defined
Error fetching Breaking the Fake News Barrier: Deep Learning Approaches in Bangla Language: name 'scholarly' is not defined
Error fetching Fake News Detection Model using Machine Learning Techniques: name 'scholarly' is not defined
Error fetching Classification of Fake News on Social Media Using BERT: name 'scholarly' is not defined
Error fetching Fake news detection method based on multi-feature fusion of entity and structured text: name 'scholarly' is not defined
Error fetching A Comparative Analysis of Machine Learning Approaches for Fake News Detection: name 'scholarly' is not defined
Error fetching Classifying True and Fake News Using LSTM Architecture: name 'scholarly' is not defined
Error fetching News Classification using Natural Language Processing: name 'scholarly' is not defined
Error fetching Toward News Authenticity: Synthesizing Natural Language Processing and Human Expert Opinion to Evaluate News: name 'scholarly' is not defined
Error fetching Exploring the Impact of Machine Translation on Fake News Detection: A Case Study on Persian Tweets about COVID-19: name 'scholarly' is not defined
Error fetching Sentiment-Aware Detection Method of Fake News Based on Linguistic Fuzzy Bi-LSTM: name 'scholarly' is not defined
Error fetching ALIKAH- A Clickbait and Fake News Detection System using Natural Language Processing: name 'scholarly' is not defined
Error fetching Natural Language Processing based Online Fake News Detection Challenges – A Detailed Review: name 'scholarly' is not defined
Error fetching Fake News Classification and Topic Modeling in Brazilian Portuguese: name 'scholarly' is not defined
Error fetching Adaptive Trans-Bidirectional Long Short Term Memory for Detecting COVID19 Epidemic Fake News on Social Media: name 'scholarly' is not defined
Error fetching EdgeFNF: Toward Real-time Fake News Detection on Mobile Edge Computing: name 'scholarly' is not defined
Error fetching Fake News Detection using Machine Learning: name 'scholarly' is not defined
Error fetching Fake News Detection using Machine Learning: name 'scholarly' is not defined
Error fetching Optimization and Improvement of Fake News Detection using Voting Technique for Societal Benefit: name 'scholarly' is not defined
Error fetching TICCA - A Co-attention Network for Multimodal Fake News Detection: name 'scholarly' is not defined
Error fetching Detecting Intents of Fake News Using Uncertainty-Aware Deep Reinforcement Learning: name 'scholarly' is not defined
Error fetching Deep learning methods for Fake News detection: name 'scholarly' is not defined
Error fetching Understanding the Applications of Natural Language Processing on COVID-19 Data: name 'scholarly' is not defined
Error fetching A Review of Deep Learning-Based Natural Language Generation Research: name 'scholarly' is not defined
Error fetching Performance Comparison of Multinomial and Bernoulli Naïve Bayes Algorithms with Laplace Smoothing Optimization in Fake News Classification: name 'scholarly' is not defined
Error fetching Fake News Detection Using A Deep Neural Network: name 'scholarly' is not defined
Error fetching Detection of Bangla Fake News using MNB and SVM Classifier: name 'scholarly' is not defined
Error fetching Novel Approach to Capture Fake News Classification Using LSTM and GRU Networks: name 'scholarly' is not defined
Error fetching Ensemble Learning-based Fake News and Disinformation Detection System: name 'scholarly' is not defined
Error fetching Online Fake News Detection using Pre-trained Embeddings: name 'scholarly' is not defined
Error fetching Enhanced Fake News Detection With Natural Language Processing: name 'scholarly' is not defined
Error fetching Fake News Detection in Hindi Using Embedding Techniques: name 'scholarly' is not defined
Error fetching Implementation of a Priority Queue to Optimize Resources during Manual Verification of Fake News: name 'scholarly' is not defined
Error fetching Toxic Fake News Detection and Classification for Combating COVID-19 Misinformation: name 'scholarly' is not defined
Error fetching Leveraging machine learning for browser-based detection of misinformation: Towards user-empowered news consumption*: name 'scholarly' is not defined
Error fetching Transforming Fake News: Robust Generalisable News Classification Using Transformers: name 'scholarly' is not defined
Error fetching Arabic Rumor Detection Using Contextual Deep Bidirectional Language Modeling: name 'scholarly' is not defined
Error fetching IEEE Xplore Search Results: name 'scholarly' is not defined
Error fetching Is it Fake? News Disinformation Detection on South African News Websites: name 'scholarly' is not defined
Error fetching Detection of Fake Users in Twitter Using Network Representation and NLP: name 'scholarly' is not defined
Error fetching Bilingual COVID-19 Fake News Detection Based on LDA Topic Modeling and BERT Transformer: name 'scholarly' is not defined
Error fetching The Sentiment of Fake News: name 'scholarly' is not defined
Error fetching Fake News Detection Using Natural Language Processing and Machine Learning Techniques: name 'scholarly' is not defined
Error fetching Health Misinformation in the Covid-19 Era - Detecting Misinformation on Bi-lingual Corpora using Lexical Features: name 'scholarly' is not defined
Error fetching Improving Arabic Fake News Detection Using Optimized Feature Selection: name 'scholarly' is not defined
Error fetching Design of a Robust Technique for Fake News Detection: name 'scholarly' is not defined
Error fetching Fake News Detection using Deep Learning: name 'scholarly' is not defined
Error fetching Fake News Detection Using Deep Learning: name 'scholarly' is not defined
Error fetching Multimodality Web Page Analysis for Fake News Detection: name 'scholarly' is not defined
Error fetching Detecting Fake News Using Machine Learning Based Approaches: name 'scholarly' is not defined
Error fetching A Multi-Modal Framework for Fake News Analysis for Detection to Deconstruction: name 'scholarly' is not defined
Error fetching Fake News Detection Using BERT-VGG19 Multimodal Variational Autoencoder: name 'scholarly' is not defined
Error fetching Fake News Detection in Social Media Using Supervised Learning Techniques: name 'scholarly' is not defined
Error fetching Fake News Detection Using Naïve Bayes and Support Vector Machine: name 'scholarly' is not defined
Error fetching Feature Integration Strategies for Multilingual Fake News Classification: name 'scholarly' is not defined
Error fetching A Hybrid Transformer-Based Model for Optimizing Fake News Detection: name 'scholarly' is not defined
Error fetching Improved Fake News Detection Method based on Deep Learning and Comparative Analysis with other Machine Learning approaches: name 'scholarly' is not defined
Error fetching Fake News Detection Using One-Class Classification: name 'scholarly' is not defined
Error fetching Effect of Text Augmentation and Adversarial Training on Fake News Detection: name 'scholarly' is not defined
Error fetching Fake News Detection with Generated Comments for News Articles: name 'scholarly' is not defined
Error fetching Identification of Fake News in Low-Resource Language: A Deep Learning Approach: name 'scholarly' is not defined
Error fetching Development of Classification Model based on Arabic Textual Analysis to Detect Fake News: Case Studies: name 'scholarly' is not defined
Error fetching Track Mendacity Broadcast using Natural Language Processing: name 'scholarly' is not defined
Error fetching Fake News Detection Using Supervised Binary Classification Techniques: name 'scholarly' is not defined
Error fetching Research on Text Classification for Identifying Fake News: name 'scholarly' is not defined
Error fetching Misinformation classification using LSTM and BERT model: name 'scholarly' is not defined
Error fetching Fake News Spotting using Interrelated Feature Selection Model using Logistic Regression: name 'scholarly' is not defined
Error fetching BERT Model for Fake News Detection Based on Social Bot Activities in the COVID-19 Pandemic: name 'scholarly' is not defined
Error fetching Adversarial Training for Fake News Classification: name 'scholarly' is not defined
Error fetching SA-Bi-LSTM: Self Attention With Bi-Directional LSTM-Based Intelligent Model for Accurate Fake News Detection to Ensured Information Integrity on Social Media Platforms: name 'scholarly' is not defined
Error fetching Fake News Detection Using Deep Learning and Transformer-Based Model: name 'scholarly' is not defined
Error fetching Detection of Fake News related to COVID-19 using Natural Language Processing: name 'scholarly' is not defined
Error fetching A Novel Framework for Fake News Detection using Double Layer BI-LSTM: name 'scholarly' is not defined
Error fetching Fake News Detection for COVID-19 Using PySpark Framework MLlib: name 'scholarly' is not defined
Error fetching Evaluating the Veracity of News Through Machine Learning Algorithms: name 'scholarly' is not defined
Error fetching Enhancing Fake News Detection by Multi-Feature Classification: name 'scholarly' is not defined
Error fetching Performance Analysis of Transformer Based Models (BERT, ALBERT, and RoBERTa) in Fake News Detection: name 'scholarly' is not defined
Error fetching COVID-19 Fake News Prediction On Social Media Data: name 'scholarly' is not defined
Error fetching Spotting Fake News: Simplified LSTM Detection: name 'scholarly' is not defined
Error fetching Identification of Fake News in Social Media Using Sentimental Analysis: name 'scholarly' is not defined
Error fetching Towards Machine Learning Explainability in Text Classification for Fake News Detection: name 'scholarly' is not defined
Error fetching Fighting Against Fake News by Connecting Machine Learning Approaches with Web3: name 'scholarly' is not defined
Error fetching Detecting the Presence of Fake News Content on Social Networking Platforms using ML & NLP: name 'scholarly' is not defined
Error fetching A Survey of Text Classification With Transformers: How Wide? How Large? How Long? How Accurate? How Expensive? How Safe?: name 'scholarly' is not defined
Error fetching Multimodal Chinese Agricultural News Classification Method Based on Interactive Attention: name 'scholarly' is not defined
Error fetching FAMOUS: Fake News Detection Model Based on Unified Key Sentence Information: name 'scholarly' is not defined
Error fetching Enhancing Fake News Detection Using Classification Algorithms and Deep Learning: name 'scholarly' is not defined
Error fetching Disinformation Classification Using Transformer based Machine Learning: name 'scholarly' is not defined
Error fetching Fake News Detection Using Deep Learning: A Systematic Literature Review: name 'scholarly' is not defined
Error fetching Realtime News Analysis using Natural Language Processing: name 'scholarly' is not defined
Error fetching AraFake: A Deep Learning Approach for Arabic Fake News Detection: name 'scholarly' is not defined
Error fetching Evaluating the Effectiveness of Hybrid Features in Fake News Detection on Social Media: name 'scholarly' is not defined
Error fetching An Empirical Investigation into Complex Fake News Detection Using the Multinomial Naïve Bayes Framework: name 'scholarly' is not defined
Error fetching Approaches towards Fake News Detection using Machine Learning and Deep Learning: name 'scholarly' is not defined
Error fetching Comparing Traditional Machine Learning Methods for COVID-19 Fake News: name 'scholarly' is not defined
Error fetching Identifying Fake News in Real Time: name 'scholarly' is not defined
Error fetching Novel Trio-Neural Network towards Detecting Fake News on Social Media: name 'scholarly' is not defined
Error fetching BERT-Based Detection of Fake Twitter Profiles: A Case Study on the Israel-Palestine War: name 'scholarly' is not defined

In [ ]:
pip install habanero pandas

Collecting habanero
  Downloading habanero-2.2.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: httpx>=0.27.2 in /usr/local/lib/python3.11/dist-packages (from habanero) (0.28.1)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.11/dist-packages (from habanero) (24.2)
Requirement already satisfied: pyyaml>=6.0.2 in /usr/local/lib/python3.11/dist-packages (from habanero) (6.0.2)
Requirement already satisfied: tqdm>=4.66.5 in /usr/local/lib/python3.11/dist-packages (from habanero) (4.67.1)
Collecting urllib3==2.2.0 (from habanero)
  Downloading urllib3-2.2.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.2->habanero) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.2->habanero) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.2->habanero) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.2->habanero) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.2->habanero) (0.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.2->habanero) (1.3.1)
Downloading habanero-2.2.0-py3-none-any.whl (28 kB)
Downloading urllib3-2.2.0-py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.9/120.9 kB 10.4 MB/s eta 0:00:00
Installing collected packages: urllib3, habanero
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.3.0
    Uninstalling urllib3-2.3.0:
      Successfully uninstalled urllib3-2.3.0
Successfully installed habanero-2.2.0 urllib3-2.2.0

In [ ]:
from habanero import Crossref
import pandas as pd

cr = Crossref()

# Load CSV with article titles
df = pd.read_csv("analyse bibliol ieee.csv")

citation_counts = []

for title in df["Title"]:
    try:
        result = cr.works(query=title)
        if "message" in result and "items" in result["message"] and len(result["message"]["items"]) > 0:
            citations = result["message"]["items"][0].get("is-referenced-by-count", 0)
            citation_counts.append(citations)
            print(f"Citations for {title}: {citations}")
        else:
            citation_counts.append(None)
    except Exception as e:
        citation_counts.append(None)
        print(f"Error fetching {title}: {e}")

# Add citation data to DataFrame
df["Citations"] = citation_counts

# Save results
df.to_csv("articles_with_citations.csv", index=False)

print("Citation data saved successfully!")

Citations for Leveraging Natural Language Processing for Detecting Fake News: A Comparative Analysis: 0
Citations for Fake News Detection Using Deep Learning and Natural Language Processing: 6
Citations for Machine Learning Techniques to Detect A Fake News In An Articles: 0
Citations for Optimization of Hugging Face Transformers for Fake News Detection: 0
Citations for Detection of Fake News with RoBERTa Based Embedding and Modified Deep Neural Network Architecture: 0
Citations for Machine Learning for Fake News Detection on Social Media Text: 0
Citations for A Comparison of Text Classification Methods: Towards Fake News Detection for Indonesian Websites: 2
Citations for RealCheck: A Web Application for Fake News Detection Using Natural Language Processing: 0
Citations for Fake News Detection Using Neural Network: 0
Citations for Comparative Analysis Of Machine Learning Models For Fake News Classification: 2
Citations for Fake News Detection Using Optimized Deep Learning Model Through Effective Feature Extraction: 1
Citations for Boosting Fake News Detection Accuracy: A Deep Dive into LSTM Classifiers: 0
Citations for Comparative Analysis of Learning Models for Solving Natural Language Processing Tasks: 0
Citations for A Comprehensive Survey on Automatic Detection of Fake News Using Natural Language Processing: Challenges and Limitations: 0
Citations for COVID-19 Fake News and Misinformation Detection using Transformer Learning: 0
Citations for Unveiling Fake News with Machine Learning and Natural Language Processing Techniques: 0
Citations for Fake News Detection using Machine Learning: 0
Citations for Advancements in Fake News Detection: Integrating NLP and Multi-Modal Approaches: 0
Citations for Active Learning for Text Classification and Fake News Detection: 9
Citations for NLP-driven Content Classification Towards Fake News and Bully Detection: 0
Citations for Systematic Literature Review on Methods used in Classification and Fake News Detection in Indonesian: 3
Citations for Memory Based Online Fake News Detection System: 0
Citations for Fake News Detection using Hybrid BiLSTM-TCN Model with Attention Mechanism: 2
Citations for Cyber Sleuth: Harnessing NLP and Blockchain for Twitter Based Fake News Detection: 0
Citations for News Category Classification using Natural Language Processing Transformer: 1
Citations for A Natural Language Processing System for Truth Detection and Text Summarization: 1
Citations for Fake news detection in Slovak language using deep learning techniques: 11
Citations for Artificial Intelligence based Fake News Classification System: 0
Citations for Identifying Inaccurate Stories: Leveraging High Knowledge and Big Data: 0
Citations for A Brazilian Portuguese Moral Foundations Dictionary for Fake News classification: 8
Citations for Natural Language Processing Approach for Fake News Detection Using Metaheuristics Optimized Extreme Gradient Boosting: 0
Citations for Classifying Fake News Detection Using SVM, Naive Bayes and LSTM: 19
Citations for Simultaneous Fake News and Topic Classification via Auxiliary Task Learning: 0
Citations for An In-depth Analysis of Transformer Models for Enhanced Performance in Fake News Detection: 0
Citations for The Use of Data Augmentation as a Technique for Improving Fake News Detection in the Romanian Language: 2
Citations for Characterization, Classification and Detection of Fake News in Online Social Media Networks: 17
Citations for Compact BERT-Based Multi-Models for Efficient Fake News Detection: 1
Citations for Fake News Detection by Using Doc2Vec Representation Model and Various Classification Algorithms: 1
Citations for Enhanced Detection of Misinformation Text-Based Fake News Analysis: 0
Citations for Fake News Detection using Voting Ensemble Classifier: 5
Citations for An Enhanced Fake News Detection System With Fuzzy Deep Learning: 0
Citations for Fake News Detection Using Machine Learning Models: 0
Citations for Data Augmentation for Fake News Using ChatGPT: 0
Citations for Deep Learning-based Text News Classification using Bi-directional LSTM Model: 0
Citations for Bangla Fake News Detection using Machine Learning, Deep Learning and Transformer Models: 2
Citations for NEWSIFY: - Article Summarization using Natural Language Processing and News Authentication using TF-IDF Vectorizer and Passive Aggressive Classifier: 0
Citations for Fake News Recognition: A Machine Learning Approach for Text Analysis using Hyperparameter Tuning: 0
Citations for Fake News Detection Using Sentiment Analysis Approach in Indonesian Language: 0
Citations for Performance Evaluation of Fake News Detection using Predictive Modeling: 1
Citations for Utilizing Word Embedding and Linguistic Features for Fake News Detection: 4
Citations for Smart Edge-based Fake News Detection using Pre-trained BERT Model: 9
Citations for Optimizing Text Classification: A Comparative Analysis of Pre-Trained Models and Custom Neural Network Architectures on the AuTextification Dataset: 0
Citations for Multilingual Misinformation Detection: Deep Learning Approaches for News Authenticity Assessment: 0
Citations for A Novel Framework for Fake News Detection Using LDA and QDA: 0
Citations for Easy Data Augmentation for Handling Imbalanced Data in Fake News Detection: 0
Citations for Performance Analysis of ML Techniques in Identification of Fake News: 6
Citations for A Hierarchical Framework for Fake News Detection Using Semantic Analysis and Source Reliability: 0
Citations for Advancing Media Integrity through AI-Powered Fake News Detection: 0
Citations for An Efficient Deep Learning Technique for Bangla Fake News Detection: 3
Citations for Exploring Hierarchical Language Knowledge in Graph Neural Networks for Fake News Detection: 0
Citations for A Study on Artificial Intelligence Techniques for Fake News Detection: 2
Citations for Comparative Study of Classification Algorithms on Contrived News: 0
Citations for Multi Class Fake News Detection using LSTM Approach: 5
Citations for Fake News Detection Approach Using Hybrid Deep Learning Framework: 0
Citations for Breaking the Fake News Barrier: Deep Learning Approaches in Bangla Language: 0
Citations for Fake News Detection Model using Machine Learning Techniques: 0
Citations for Classification of Fake News on Social Media Using BERT: 0
Citations for Fake news detection method based on multi-feature fusion of entity and structured text: 0
Citations for A Comparative Analysis of Machine Learning Approaches for Fake News Detection: 0
Citations for Classifying True and Fake News Using LSTM Architecture: 0
Citations for News Classification using Natural Language Processing: 0
Citations for Toward News Authenticity: Synthesizing Natural Language Processing and Human Expert Opinion to Evaluate News: 8
Citations for Exploring the Impact of Machine Translation on Fake News Detection: A Case Study on Persian Tweets about COVID-19: 3
Citations for Sentiment-Aware Detection Method of Fake News Based on Linguistic Fuzzy Bi-LSTM: 0
Citations for ALIKAH- A Clickbait and Fake News Detection System using Natural Language Processing: 1
Citations for Natural Language Processing based Online Fake News Detection Challenges – A Detailed Review: 15
Citations for Fake News Classification and Topic Modeling in Brazilian Portuguese: 5
Citations for Adaptive Trans-Bidirectional Long Short Term Memory for Detecting COVID19 Epidemic Fake News on Social Media: 0
Citations for EdgeFNF: Toward Real-time Fake News Detection on Mobile Edge Computing: 3
Citations for Fake News Detection using Machine Learning: 0
Citations for Fake News Detection using Machine Learning: 0
Citations for Optimization and Improvement of Fake News Detection using Voting Technique for Societal Benefit: 2
Citations for TICCA - A Co-attention Network for Multimodal Fake News Detection: 2
Citations for Detecting Intents of Fake News Using Uncertainty-Aware Deep Reinforcement Learning: 0
Citations for Deep learning methods for Fake News detection: 1
Citations for Understanding the Applications of Natural Language Processing on COVID-19 Data: 11
Citations for A Review of Deep Learning-Based Natural Language Generation Research: 0
Citations for Performance Comparison of Multinomial and Bernoulli Naïve Bayes Algorithms with Laplace Smoothing Optimization in Fake News Classification: 0
Citations for Fake News Detection Using A Deep Neural Network: 51
Citations for Detection of Bangla Fake News using MNB and SVM Classifier: 57
Citations for Novel Approach to Capture Fake News Classification Using LSTM and GRU Networks: 1
Citations for Ensemble Learning-based Fake News and Disinformation Detection System: 4
Citations for Online Fake News Detection using Pre-trained Embeddings: 2
Citations for Enhanced Fake News Detection With Natural Language Processing: 0
Citations for Fake News Detection in Hindi Using Embedding Techniques: 3
Citations for Implementation of a Priority Queue to Optimize Resources during Manual Verification of Fake News: 0
Citations for Toxic Fake News Detection and Classification for Combating COVID-19 Misinformation: 0
Citations for Leveraging machine learning for browser-based detection of misinformation: Towards user-empowered news consumption*: 0
Citations for Transforming Fake News: Robust Generalisable News Classification Using Transformers: 10
Citations for Arabic Rumor Detection Using Contextual Deep Bidirectional Language Modeling: 4
Citations for IEEE Xplore Search Results: 0
Citations for Is it Fake? News Disinformation Detection on South African News Websites: 4
Citations for Detection of Fake Users in Twitter Using Network Representation and NLP: 6
Citations for Bilingual COVID-19 Fake News Detection Based on LDA Topic Modeling and BERT Transformer: 4
Citations for The Sentiment of Fake News: 80
Citations for Fake News Detection Using Natural Language Processing and Machine Learning Techniques: 0
Citations for Health Misinformation in the Covid-19 Era - Detecting Misinformation on Bi-lingual Corpora using Lexical Features: 1
Citations for Improving Arabic Fake News Detection Using Optimized Feature Selection: 4
Citations for Design of a Robust Technique for Fake News Detection: 0
Citations for Fake News Detection using Deep Learning: 2
Citations for Fake News Detection Using Deep Learning: 2
Citations for Multimodality Web Page Analysis for Fake News Detection: 0
Citations for Detecting Fake News Using Machine Learning Based Approaches: 0
Citations for A Multi-Modal Framework for Fake News Analysis for Detection to Deconstruction: 0
Citations for Fake News Detection Using BERT-VGG19 Multimodal Variational Autoencoder: 6
Citations for Fake News Detection in Social Media Using Supervised Learning Techniques: 2
Citations for Fake News Detection Using Naïve Bayes and Support Vector Machine: 0
Citations for Feature Integration Strategies for Multilingual Fake News Classification: 0
Citations for A Hybrid Transformer-Based Model for Optimizing Fake News Detection: 0
Citations for Improved Fake News Detection Method based on Deep Learning and Comparative Analysis with other Machine Learning approaches: 2
Citations for Fake News Detection Using One-Class Classification: 14
Citations for Effect of Text Augmentation and Adversarial Training on Fake News Detection: 0
Citations for Fake News Detection with Generated Comments for News Articles: 23
Citations for Identification of Fake News in Low-Resource Language: A Deep Learning Approach: 0
Citations for Development of Classification Model based on Arabic Textual Analysis to Detect Fake News: Case Studies: 1
Citations for Track Mendacity Broadcast using Natural Language Processing: 1
Citations for Fake News Detection Using Supervised Binary Classification Techniques: 0
Citations for Research on Text Classification for Identifying Fake News: 7
Citations for Misinformation classification using LSTM and BERT model: 0
Citations for Fake News Spotting using Interrelated Feature Selection Model using Logistic Regression: 0
Citations for BERT Model for Fake News Detection Based on Social Bot Activities in the COVID-19 Pandemic: 34
Citations for Adversarial Training for Fake News Classification: 5
Citations for SA-Bi-LSTM: Self Attention With Bi-Directional LSTM-Based Intelligent Model for Accurate Fake News Detection to Ensured Information Integrity on Social Media Platforms: 1
Citations for Fake News Detection Using Deep Learning and Transformer-Based Model: 4
Citations for Detection of Fake News related to COVID-19 using Natural Language Processing: 1
Citations for A Novel Framework for Fake News Detection using Double Layer BI-LSTM: 3
Citations for Fake News Detection for COVID-19 Using PySpark Framework MLlib: 0
Citations for Evaluating the Veracity of News Through Machine Learning Algorithms: 0
Citations for Enhancing Fake News Detection by Multi-Feature Classification: 7
Citations for Performance Analysis of Transformer Based Models (BERT, ALBERT, and RoBERTa) in Fake News Detection: 9
Citations for COVID-19 Fake News Prediction On Social Media Data: 2
Citations for Spotting Fake News: Simplified LSTM Detection: 0
Citations for Identification of Fake News in Social Media Using Sentimental Analysis: 2
Citations for Towards Machine Learning Explainability in Text Classification for Fake News Detection: 10
Citations for Fighting Against Fake News by Connecting Machine Learning Approaches with Web3: 3
Citations for Detecting the Presence of Fake News Content on Social Networking Platforms using ML & NLP: 1
Citations for A Survey of Text Classification With Transformers: How Wide? How Large? How Long? How Accurate? How Expensive? How Safe?: 9
Citations for Multimodal Chinese Agricultural News Classification Method Based on Interactive Attention: 0
Citations for FAMOUS: Fake News Detection Model Based on Unified Key Sentence Information: 5
Citations for Enhancing Fake News Detection Using Classification Algorithms and Deep Learning: 1
Citations for Disinformation Classification Using Transformer based Machine Learning: 0
Citations for Fake News Detection Using Deep Learning: A Systematic Literature Review: 1
Citations for Realtime News Analysis using Natural Language Processing: 0
Citations for AraFake: A Deep Learning Approach for Arabic Fake News Detection: 1
Citations for Evaluating the Effectiveness of Hybrid Features in Fake News Detection on Social Media: 0
Citations for An Empirical Investigation into Complex Fake News Detection Using the Multinomial Naïve Bayes Framework: 0
Citations for Approaches towards Fake News Detection using Machine Learning and Deep Learning: 2
Citations for Comparing Traditional Machine Learning Methods for COVID-19 Fake News: 9
Citations for Identifying Fake News in Real Time: 1
Citations for Novel Trio-Neural Network towards Detecting Fake News on Social Media: 4
Citations for BERT-Based Detection of Fake Twitter Profiles: A Case Study on the Israel-Palestine War: 0
Citations for An Arabic Corpus for Covid-19 related Fake News: 3
Citations for A Study of Cantonese Covid-19 Fake News Detection on Social Media: 3
Citations for COVID-19 Fake News Detection on Social Media: 0
Citations for A Framework for Automatic Fake Content Identification: 0
Citations for Fake News Detection using Machine Learning and Natural Language Processing: 0
Citations for Natural Language Contents Evaluation System for Detecting Fake News using Deep Learning: 14
Citations for Navigating the Gray Area: A Three-Label Framework for Uncovering Uncertainty in Fake News: 0
Citations for Rumor detection and combat through Machine Learning: 0
Citations for On Truth Discrimination of Media News Related to Rumor and Fake News by LSTM: 0
Citations for Detecting Fake News in Benchmark English News Dataset Using Machine Learning Classifiers: 3
Citations for Utilization Strategy of User Engagements in Korean Fake News Detection: 5
Citations for Anempirical Analysis of Classification Models for Detection of Fake News Articles: 5
Citations for Enhancing Machine-Generated Text Detection: Adversarial Fine-Tuning of Pre-Trained Language Models: 0
Citations for A Multi-Kernel Optimized Convolutional Neural Network With Urdu Word Embedding to Detect Fake News: 1
Citations for Machine Learning Approaches for Fake News Detection: A Review: 10
Citations for IEEE Xplore Search Results: 0
Citations for Towards Fake News Identification using Machine Learning: 1
Citations for Interpretable AI Insights in Fake News Detection: A Comparative Analysis of CNN and LSTM: 0
Citations for Sentiment Analysis Model for Fake News Identification in Arabic Tweets: 3
Citations for Towards Automated Claim Detection In Fact Checking: 0
Citations for Unveiling Fake News: A Machine and Deep Learning Approach: 0
Citations for Rumor Stance Classification: A Case Study on the Propagation of Political Rumors on the Algerian Online Social Space: 0
Citations for Implementation of Fake News Detection Using Long Short Term Memory Method Base on Android: 0
Citations for Fake News Detection using Machine Learning: 0
Citations for Classifying Real and Bot Users Based on their News Spread for Combating Misinformation: 1
Citations for Arabic Fake News and Spam Handling: Methods, Resources and Opportunities: 2
Citations for Arabic Fake News Detection using Ensemble Technique: 0
Citations for Context-Aware Misinformation Detection: A Benchmark of Deep Learning Architectures Using Word Embeddings: 31
Citations for Fake News detection Using Machine Learning: 0
Citations for Detecting Fake News and Performing Quality Ranking of German Newspapers Using Machine Learning: 1
Citations for Classification of Fake News on Facebook a Novel Social Network with K-Means Clustering Approach for Against Principal Component Analysis Method for Better Accuracy: 2
Citations for An Effective Assessment of Machine Learning Approaches for Fake News Detection: 0
Citations for Detecting Fake News using Advanced Language Models: BERT and RoBERTa: 0
Citations for RoBERTa-GCN: A Novel Approach for Combating Fake News in Bangla Using Advanced Language Processing and Graph Convolutional Networks: 0
Citations for Fake News Detection Using Machine Learning and Deep Learning Algorithms: 18
Citations for Fake News Detection using Machine Learning Algorithms: 0
Citations for Prompt Learning for Low-Resource Multi-Domain Fake News Detection: 1
Citations for LSTM Based Approach to Detect Fake News: 1
Citations for NLP and Deep Learning for Fake News Classification: 0
Citations for An Improved and Efficient Technique for detecting Bengali Fake News using Machine Learning Algorithms: 5
Citations for Cyberspace News Prediction of Text and Image with Report Generation: 1
Citations for Detection Of Online Fake News : A Survey: 0
Citations for Unraveling Deception: Pioneering Machine Learning Solutions for Authenticating News in Evolving Social Media Landscapes: 0
Citations for Utilizing Ensemble Learning for Detecting Multi-Modal Fake News: 6
Citations for Employment of Distinct Machine Learning Algorithms for Predicting Fake Tweets: 0
Citations for Inductive Logic Programming based Bottlenose Delphin Optimization to Fake new Detection: 0
Citations for Feature Selection for Fake News Classification: 0
Citations for Fake News Detection: A Comparative Study of Machine Learning Techniques: 18
Citations for Cross comparison of COVID-19 fake news detection machine learning models: 0
Citations for Automated Method for Fake News Detection Using Machine Learning: 1
Citations for A comparative analysis of Graph Neural Networks and commonly used machine learning algorithms on fake news detection: 8
Citations for A Hybrid DistilBERT-BiGRU Model for Enhanced Misinformation Detection: Leveraging Transformer-Based Pretraining Language Model: 0
Citations for Fraudulent News Detection using Machine Learning Approaches: 4
Citations for Fake Media Detection Based on Natural Language Processing and Blockchain Approaches: 0

In [ ]:
df

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body,Citations
0,H6LVW46C,conferencePaper,2024.0,"Vadakkethil Somanathan Pillai, Sanjaikanth E; ...",Leveraging Natural Language Processing for Det...,2024 2nd International Conference on Disruptiv...,NaN,NaN,10.1109/ICDT61202.2024.10489386,https://ieeexplore.ieee.org/document/10489386/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,QFSGAUXJ,conferencePaper,2022.0,"Matheven, Anand; Kumar, Burra Venkata Durga",Fake News Detection Using Deep Learning and Na...,2022 9th International Conference on Soft Comp...,NaN,NaN,10.1109/ISCMI56532.2022.10068440,https://ieeexplore.ieee.org/document/10068440/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
2,8RC5I9RH,conferencePaper,2024.0,"Nirmala, M; Navya, R",Machine Learning Techniques to Detect A Fake N...,2024 Second International Conference on Networ...,NaN,NaN,10.1109/NMITCON62075.2024.10699063,https://ieeexplore.ieee.org/document/10699063/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,IUU7DPFA,conferencePaper,2023.0,"Misra, Shamik; Tandon, Prabhat; Panda, Purna C...",Optimization of Hugging Face Transformers for ...,"2023 International Conference on Data Science,...",NaN,NaN,10.1109/ICDSAAI59313.2023.10452606,https://ieeexplore.ieee.org/document/10452606/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,3PDRPNI8,conferencePaper,2023.0,"Rakib Mollah, Md. Abdur; Kabir, Mir Md. Jahang...",Detection of Fake News with RoBERTa Based Embe...,2023 26th International Conference on Computer...,NaN,NaN,10.1109/ICCIT60459.2023.10441206,https://ieeexplore.ieee.org/document/10441206/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,7TMQ58DZ,conferencePaper,2023.0,"Misini, Arta; Kadriu, Arbana; Canhasi, Ercan",Albanian Authorship Attribution Model,2023 12th Mediterranean Conference on Embedded...,NaN,NaN,10.1109/MECO58584.2023.10155046,https://ieeexplore.ieee.org/document/10155046/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
725,E9BY98BZ,journalArticle,2020.0,"Kausar, Soufia; Tahir, Bilal; Mehmood, Muhamma...",ProSOUL: A Framework to Identify Propaganda Fr...,IEEE Access,NaN,2169-3536,10.1109/ACCESS.2020.3028131,https://ieeexplore.ieee.org/document/9210545/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
726,7AVYRDYK,conferencePaper,2023.0,"Pal, Satinder; Lamba, Anil Kumar",Tweeting Truth: Investigating False Informatio...,2023 IEEE World Conference on Applied Intellig...,NaN,NaN,10.1109/AIC57670.2023.10263951,https://ieeexplore.ieee.org/document/10263951/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
727,KFRUP6E2,conferencePaper,2024.0,"Chauhan, Shubham; Verma, Shija; Pandey, Ayushi...",Media Bias Monitor: Quantifying Biases of Indi...,2024 15th International Conference on Computin...,NaN,NaN,10.1109/ICCCNT61001.2024.10724364,https://ieeexplore.ieee.org/document/10724364/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
728,2AHV8G2Z,webpage,NaN,NaN,IEEE Xplore Search Results,NaN,NaN,NaN,NaN,https://ieeexplore.ieee.org/search/searchresul...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
import pandas as pd
from google.colab import files

# Upload CSV files
uploaded = files.upload()

Saving google scholar biblio.csv to google scholar biblio.csv

In [ ]:
import pandas as pd
from google.colab import files

# Upload CSV files
uploaded = files.upload()

Saving google scholar biblio.csv to google scholar biblio.csv

In [ ]:
df = pd.read_csv("google scholar biblio.csv")

In [ ]:
df

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
0,I4RA2AQR,journalArticle,2021.0,"Bangyal, Waqas Haider; Qasim, Rukhma; Rehman, ...",Detection of Fake News Text Classification on ...,Computational and Mathematical Methods in Medi...,NaN,"1748-6718, 1748-670X",10.1155/2021/5514220,https://www.hindawi.com/journals/cmmm/2021/551...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F6I8N2RH,preprint,2022.0,"Ahmed, Sajjad; Hinkelmann, Knut; Corradini, Fl...",Development of Fake News Model using Machine L...,NaN,NaN,NaN,10.48550/arXiv.2201.07489,http://arxiv.org/abs/2201.07489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BKBUQTDX,journalArticle,2020.0,"Su, Qi; Wan, Mingyu; Liu, Xiaoqian; Huang, Chu...","Motivations, methods and metrics of misinforma...",Natural Language Processing Research,NaN,NaN,NaN,https://ira.lib.polyu.edu.hk/handle/10397/92407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ZNDUD74T,journalArticle,2022.0,"Prachi, Noshin Nirvana; Habibullah, Md; Rafi, ...",Detection of Fake News Using Machine Learning ...,Journal of Advances in Information Technology,NaN,NaN,NaN,https://www.researchgate.net/profile/Riasat-Kh...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HG6CPVWM,journalArticle,2021.0,"de Oliveira, Nicollas R.; Pisa, Pedro S.; Lope...",Identifying fake news on social networks based...,Information,NaN,NaN,NaN,https://www.mdpi.com/2078-2489/12/1/38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,YSYK2AJC,conferencePaper,2021.0,"Kaliyar, Rohit Kumar; Fitwe, Kedar; Rajarajesw...",Classification of Hoax/Non-Hoax news articles ...,2021 5th International Conference on Computing...,NaN,NaN,NaN,https://ieeexplore.ieee.org/abstract/document/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,WZMBBINI,journalArticle,2021.0,"Paschalides, Demetris; Christodoulou, Chrysova...",Check-It: A plugin for detecting fake news on ...,Online Social Networks and Media,NaN,NaN,NaN,https://www.sciencedirect.com/science/article/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2YAQMYFE,bookSection,2023.0,"Mirnalinee, T. T.; Jayaraman, Bhuvana; Anirudh...",A Novel Dataset for Fake News Detection in Tam...,Speech and Language Technologies for Low-Resou...,978-3-031-33230-2 978-3-031-33231-9,NaN,NaN,https://link.springer.com/10.1007/978-3-031-33...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,W8LHSENN,document,2023.0,"Mengoni, Paolo; Santucci, Valentino",Special Issue “Recent Trends in Natural Langua...,NaN,NaN,NaN,NaN,https://www.mdpi.com/2076-3417/13/12/7284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
969,SIY8IVA7,bookSection,2021.0,"Selva Birunda, S.; Kanniga Devi, R.",A Review on Word Embedding Techniques for Text...,Innovative Data Communication Technologies and...,978-981-15-9650-6 978-981-15-9651-3,NaN,NaN,https://link.springer.com/10.1007/978-981-15-9...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from habanero import Crossref
import pandas as pd

cr = Crossref()

# Load CSV with article titles
df = pd.read_csv("google scholar biblio.csv")

citation_counts = []

for title in df["Title"]:
    try:
        result = cr.works(query=title)
        if "message" in result and "items" in result["message"] and len(result["message"]["items"]) > 0:
            citations = result["message"]["items"][0].get("is-referenced-by-count", 0)
            citation_counts.append(citations)
            print(f"Citations for {title}: {citations}")
        else:
            citation_counts.append(None)
    except Exception as e:
        citation_counts.append(None)
        print(f"Error fetching {title}: {e}")

# Add citation data to DataFrame
df["Citations"] = citation_counts

# Save results
df.to_csv("articles_with_citations_google scholar.csv", index=False)

print("Citation data saved successfully!")

Citations for Detection of Fake News Text Classification on COVID-19 Using Deep Learning Approaches: 68
Citations for Development of Fake News Model using Machine Learning through Natural Language Processing: 0
Citations for Motivations, methods and metrics of misinformation detection: an NLP perspective: 35
Citations for Detection of Fake News Using Machine Learning and Natural Language Processing Algorithms [J]: 0
Citations for Identifying fake news on social networks based on natural language processing: trends and challenges: 0
Citations for A Machine Learning Approach to Fake News Detection Using Knowledge Verification and Natural Language Processing: 0
Citations for Fake news classification based on content level features: 31
Citations for Fake news detection using machine learning and natural language processing: 0
Citations for Natural Language Processing with Optimal Deep Learning Based Fake News Classification.: 3
Citations for A Literature Review of NLP Approaches to Fake News Detection and Their Applicability to RomanianLanguage News Analysis.: 8
Citations for Thai Fake News Detection Based on Information Retrieval, Natural Language Processing and Machine Learning: 38
Citations for Fake news detection using deep learning integrating feature extraction, natural language processing, and statistical descriptors: 7
Citations for Natural language processing based online fake news detection challenges–A detailed review: 15
Citations for Fake News Detection Using Feature Extraction, Natural Language Processing, Curriculum Learning, and Deep Learning: 3
Citations for Fake news detection using machine learning approaches: 10
Citations for Towards machine learning explainability in text classification for fake news detection: 10
Citations for Active learning for text classification and fake news detection: 9
Citations for Stylometric fake news detection based on natural language processing using named entity recognition: In-domain and cross-domain analysis: 3
Citations for FakeWhastApp. BR: NLP and Machine Learning Techniques for Misinformation Detection in Brazilian Portuguese WhatsApp Messages.: 3
Citations for Rapid detection of fake news based on machine learning methods: 21
Citations for Fake News Detection in Social Media using Graph Neural Networks and NLP Techniques: A COVID-19 Use-case: 4
Citations for Fake media detection based on natural language processing and blockchain approaches: 0
Citations for Hong Kong Protests: Using Natural Language Processing for Fake News Detection on Twitter: 18
Citations for Deep neural approach to Fake-News identification: 51
Citations for A comprehensive review on fake news detection with deep learning: 0
Citations for Integration of nlp and deep learning for automated fake news detection: 0
Citations for Identifying fake news in Indonesian via supervised binary text classification: 18
Citations for Operating machine learning across natural language processing techniques for improvement of fabricated news model: 10
Citations for A survey on role of machine learning and nlp in fake news detection on social media: 2
Citations for Fake news detection using deep learning and natural language processing: 6
Citations for Fighting post-truth using natural language processing: A review and open challenges: 50
Citations for A Dynamic Approach for Detecting the Fake News Using Random Forest Classifier and NLP: 15
Citations for Exploring the efficacy of natural language processing and supervised learning in the classification of fake news articles: 0
Citations for Fake news detection using deep learning: 2
Citations for Persian Fake News Detection: Neural Representation and Classification at Word and Text Levels: 5
Citations for Identification of fake news using machine learning: 0
Citations for Fake news detection: Taxonomy and comparative study: 0
Citations for The influence of fake news on social media: analysis and verification of web content during the COVID-19 pandemic by advanced machine learning methods and natural language processing: 19
Citations for Fake news identification on social media: 4
Citations for New explainability method for BERT-based model in fake news detection: 59
Citations for Fake News Identification Through Natural Language Processing and Machine Learning Approach: 0
Citations for An overview of online fake news: Characterization, detection, and discussion: 539
Citations for A transformer-based architecture for fake news classification: 34
Citations for Enhancing fake news detection by multi-feature classification: 7
Citations for Technical solution to counter potential crime: Text analysis to detect fake news and disinformation: 16
Citations for Automated hybrid Deep Neural Network model for fake news identification and classification in social networks: 0
Citations for Fake news detection on social media using a natural language inference approach: 3
Citations for Fake news detection in multiple platforms and languages: 112
Citations for NLP-based feature extraction for the detection of COVID-19 misinformation videos on YouTube: 0
Citations for Fake news detection using NLP: 1
Citations for Application of the BERT-Based Architecture in Fake News Detection: 27
Citations for Advanced Machine Learning techniques for fake news (online disinformation) detection: A systematic mapping study: 72
Citations for Fake News Types and Detection Models on Social Media A State-of-the-Art Survey: 24
Citations for Machine learning techniques for the classification of fake news: 0
Citations for A meta-analysis of state-of-the-art automated fake news detection methods: 6
Citations for Natural Language Processing Approach for Fake News Detection Using Metaheuristics Optimized Extreme Gradient Boosting: 0
Citations for Fake news detection using machine learning: 0
Citations for Sentiment analysis for fake news detection: 80
Citations for Deep contextualized text representation and learning for fake news detection: 57
Citations for Using of n-grams from morphological tags for fake news classification: 0
Citations for Text classification by using natural language processing: 0
Citations for Analyzing and distinguishing fake and real news to mitigate the problem of disinformation: 17
Citations for AFND: Arabic fake news dataset for the detection and classification of articles credibility: 0
Citations for Automated classification of fake news spreaders to break the misinformation chain: 16
Citations for Developing a fake news identification model with advanced deep languagetransformers for Turkish COVID-19 misinformation data: 9
Citations for Automated Identification of Social Media Bots Using Deepfake Text Detection: 5
Citations for Detection of hyperpartisan news articles using natural language processing technique: 13
Citations for Ternion: An autonomous model for fake news detection: 30
Citations for A taxonomy of fake news classification techniques: Survey and implementation aspects: 32
Citations for Fake news detection using discourse segment structure analysis: 16
Citations for Detection of Fake Job Postings by Utilizing Machine Learning and Natural Language Processing Approaches: 25
Citations for An Approach Utilizing Linguistic Features for Fake News Detection: 4
Citations for Fake News Detection Using Machine Learning and Natural Language Processing: 0
Citations for Fake news detection based on news content and social contexts: a transformer-based approach: 125
Citations for A deep neural network-based approach for fake news detection in regional language: 4
Citations for Content-based fake news detection with machine and deep learning: a systematic review: 42
Citations for DEAP-FAKED: Knowledge graph based approach for fake news detection: 28
Citations for Robust multi-domain descriptive text classification leveraging conventional and hybrid deep learning models: 3
Citations for Fake or not? Automated detection of COVID-19 misinformation and disinformation in social networks and digital media: 6
Citations for Infodemia, fake news and medicine: science and the quest for truth: 13
Citations for Evaluating Deep Learning Approaches for Covid19 Fake News Detection: 0
Citations for Fake news detection based on deep learning: 2
Citations for Fake news detection: A hybrid CNN-RNN based deep learning approach: 268
Citations for Multimodal fake news detection: 0
Citations for Fake News Classification using transformer based enhanced LSTM and BERT: 54
Citations for HyproBert: a fake news detection model based on deep hypercontext: 13
Citations for The Surprising Performance of Simple Baselines for Misinformation Detection: 27
Citations for Deep learning for fake news detection: Literature review: 1
Citations for Fake news detection using machine learning: 0
Citations for Bengali fake news detection: 19
Citations for Optimization and improvement of fake news detection using deep learning approaches for societal benefit: 48
Citations for Sentiment Analysis for Fake News Detection by Means of Neural Networks: 34
Citations for Application of Neural Networks to Identify of Fake News.: 0
Citations for Linguistic features based framework for automatic fake news detection: 29
Citations for A Fine-Tuned BERT-Based Transfer Learning Approach for Text Classification: 78
Citations for Semantic graph based topic modelling framework for multilingual fake news detection: 8
Citations for What the fake? Probing misinformation detection standing on the shoulder of novelty and emotion: 34
Citations for Fake news spreaders detection: Sometimes attention is not all you need: 19
Citations for Automatic Fake News Detection with Pre-trained Transformer Models: 0
Citations for Cross-language fake news detection: 0
Citations for Certain Investigation of Fake News Detection from Facebook and Twitter Using Artificial Intelligence Approach: 6
Citations for Classification of Misinformation in New Articles using Natural Language Processing and a Recurrent Neural Network: 0
Citations for Toxic Fake News Detection and Classification for Combating COVID-19 Misinformation: 0
Citations for Attention-based C-BiLSTM for fake news detection: 52
Citations for Bibliometric survey on incremental learning in text classification algorithms for false information detection: 80
Citations for Fake news detection using machine learning models: 0
Citations for Improvement of misleading and fake news classification for flective languages by morphological group analysis: 24
Citations for Fake news detection using machine learning algorithms: 0
Citations for DETECTION OF FAKE NEWS USING NLP AND VARIOUS SINGLE AND ENSEMBLE LEARNING CLASSIFIERS: 1
Citations for Analysis of text feature extractors using deep learning on fake news: 22
Citations for Disinformation detection on social media: An integrated approach: 7
Citations for Multilingual deep learning framework for fake news detection using capsule neural network: 11
Citations for Arabic fake news detection based on deep contextualized embedding models: 38
Citations for Multimodal Fake News Detection: 0
Citations for Arabic Fake News Detection Based on Textual Analysis: 32
Citations for Real time fake news detection using machine learning and NLP: 1
Citations for Meta-Path-based Fake News Detection Leveraging Multi-level Social Context Information: 12
Citations for Text-mining-based Fake News Detection Using Ensemble Methods: 71
Citations for An ensemble technique to detect fabricated news article using machine learning and natural language processing techniques: 10
Citations for Effect of corpora on classification of fake news using naive Bayes classifier: 11
Citations for The Impact of Pre-processing on the Performance of Automated Fake News Detection: 2
Citations for Classification of fake news using multi-layer perceptron: 11
Citations for Detection of Turkish Fake News in Twitter with Machine Learning Algorithms: 0
Citations for Automating fake news detection system using multi-level voting model: 111
Citations for Survey on Fake News Detection Techniques: 0
Citations for A comparative study of machine learning and deep learning techniques for fake news detection: 18
Citations for Identifying Misinformation on YouTube through Transcript Contextual Analysis with Transformer Models: 0
Citations for Disinformation Detection: Knowledge Infusion with Transfer Learning and Visualizations: 3
Citations for The limitations of stylometry for detecting machine-generated fake news: 44
Citations for WELFake: word embedding over linguistic features for fake news detection: 0
Citations for Fake news detection on reddit utilising countvectorizer and term frequency-inverse document frequency with logistic regression, multinominalnb and support vector machine: 12
Citations for Detection of fake news and hate speech for Ethiopian languages: a systematic review of the approaches: 18
Citations for A tool for fake news detection using machine learning techniques: 0
Citations for Fake News Detection Using Machine Learning Methods: 0
Citations for Detecting fake news on twitter using machine learning models: 4
Citations for NITP-AI-NLP@ UrduFake-FIRE2020: Multi-layer Dense Neural Network for Fake News Detection in Urdu News Articles.: 8
Citations for A novel approach to fake news classification using LSTM-based deep learning models: 3
Citations for Problem Understanding of Fake News Detection from a Data Mining Perspective: 7
Citations for Fake news detection within online social media using supervised artificial intelligence algorithms: 243
Citations for Comparison of machine learning algorithms for sentiment classification on fake news detection: 5
Citations for Analyzing Machine Learning Enabled Fake News Detection Techniques for Diversified Datasets: 44
Citations for FakeGPT: Fake News Generation, Explanation and Detection of Large Language Models: 1
Citations for Context-based fake news detection model relying on deep learning models: 24
Citations for A comprehensive survey on machine learning approaches for fake news detection: 3
Citations for Towards Detection of AI-Generated Texts and Misinformation: 3
Citations for A Systematic Review on the Detection of Fake News Articles: 0
Citations for Integrating Machine Learning Techniques in Semantic Fake News Detection: 34
Citations for The COVID-19 fake news detection in Thai social texts: 15
Citations for Identifying Fake News in Brazilian Portuguese: 8
Citations for Lux (linguistic aspects under examination): Discourse analysis for automatic fake news classification: 3
Citations for Fake news detection in Dravidian languages using transfer learning with adaptive finetuning: 11
Citations for Artificial intelligence in automated detection of disinformation: a thematic analysis: 9
Citations for Alphabet flatting as a variant of n-gram feature extraction method in ensemble classification of fake news: 11
Citations for Detection of fake news using transformer model: 11
Citations for Detection and identification of fake news: binary content classification with pre-trained language models: 0
Citations for Automated Fake News Detection Using Computational Forensic Linguistics: 3
Citations for Characterization, classification and detection of fake news in online social media networks: 17
Citations for Fake news detection using natural language processing and logistic regression: 1
Citations for An efficient fake news detector: 7
Citations for Fake news classification using random forest and decision tree (j48): 30
Citations for Deep learning and natural language processing for fake news detection: a survey: 9
Citations for Fake News Detection: a comparison between available Deep Learning techniques in vector space: 13
Citations for The Challenges of Machine Learning for Trust and Safety: A Case Study on Misinformation Detection: 0
Citations for A hybrid method for fake news detection using cosine similarity scores: 4
Citations for Advanced Misinformation Detection: A Bi-LSTM Model Optimized by Genetic Algorithms: 2
Citations for Deep Dive into Fake News Detection: Feature-Centric Classification with Ensemble and Deep Learning Methods: 4
Citations for A fake news detection system based on combination of word embedded techniques and hybrid deep learning model: 19
Citations for Comparative analysis of machine learning algorithms to detect fake news: 4
Citations for Fake news detection using naive bayes: 329
Citations for Indobert for indonesian fake news detection: 0
Citations for Exploiting Textual Information for Fake News Detection: 3
Citations for Fake news detection on the web: An LSTM-based approach: 4
Citations for Bangla fake news detection using machine learning, deep learning and transformer models: 2
Citations for Approaches towards Fake news detection using machine learning and deep learning: 2
Citations for Fake news detection using machine learning: an adversarial collaboration approach: 2
Citations for Deep Learning with Self-Attention Mechanism for Fake News Detection: 8
Citations for Fake news detection from online media using machine learning classifiers: 13
Citations for Fake news and hate speech detection with machine learning and NLP: 0
Citations for Fake Detect: A Deep Learning Ensemble Model for Fake News Detection: 72
Citations for Fake news stance detection using selective features and FakeNET: 3
Citations for Arabic Fake News Detection: Comparative Study of Neural Networks and Transformer‐Based Approaches: 40
Citations for A Comparative Study of Hybrid Machine Learning Approaches for Fake News Detection that Combine Multi-Stage Ensemble Learning and NLP-based Framework: 2
Citations for NLP Based Fake News Detection Using Hybrid Machine Learning Techniques: 1
Citations for Fake News Detection: Do Complex Problems Need Complex Solutions?: 1
Citations for Performance comparison of machine learning classifiers for fake news detection: 36
Citations for Enhanced Fake News Detection With Natural Language Processing: 0
Citations for Understanding the applications of natural language processing on COVID-19 data: 11
Citations for A study of algorithm-based detection of fake news in brazilian election: Is bert the best: 1
Citations for nlpt malayalm@ DravidianLangTech: Fake news detection in Malayalam using optimized XLM-RoBERTa model: 0
Citations for Fake news stance detection using deep learning architecture (CNN-LSTM): 172
Citations for Bio-Inspired Artificial Intelligence with Natural Language Processing Based on Deceptive Content Detection in Social Networking: 3
Citations for Advancing fake news detection: hybrid deep learning with fasttext and explainable AI: 13
Citations for Fake news detection system using featured-based optimized msvm classification: 9
Citations for Fake News Classification: A Quantitative Research Description: 4
Citations for A survey on explainable fake news detection: 0
Citations for A review of fake news detection using machine learning techniques: 0
Citations for Fake news classification bimodal using convolutional neural network and long short-term memory: 0
Citations for BerConvoNet: A deep learning framework for fake news classification: 47
Citations for A Survey on Stance Detection for Mis- and Disinformation Identification: 22
Citations for AI tools on fake news detection: An overview and comparative study: 0
Citations for Classifying fake news articles using natural language processing and supervised learning estimator: 33
Citations for Fake News Detection in low-resourced languages “Kurdish language” using Machine learning algorithms: 0
Citations for Detection and Resolution of Rumors and Misinformation with NLP: 0
Citations for NLP in Fake News Detection: An Ensemble Deep Learning Approach in Style Based and Truth Based Detection: 1
Citations for A survey on recent advances in machine learning techniques for fake news detection: 1
Citations for Contrastive Domain Adaptation for Early Misinformation Detection: A Case Study on COVID-19: 16

In [ ]:
import pandas as pd
from google.colab import files

# Upload CSV files
uploaded = files.upload()

Saving scopus.csv to scopus.csv

In [ ]:
from habanero import Crossref
import pandas as pd

cr = Crossref()

# Load CSV with article titles
df = pd.read_csv("scopus.csv")

In [ ]:
df

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,Page count,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID
0,Tran V.H.; Sebastian Y.; Karim A.; Azam S.,"Tran, Van Hieu (59492326200); Sebastian, Yakub...",59492326200; 25923085000; 57206327767; 5489463...,Distinguishing Human Journalists from Artifici...,2024,Computers,13,12,328,NaN,NaN,NaN,0,10.3390/computers13120328,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-85213415294
1,Saheb T.; Sidaoui M.; Schmarzo B.,"Saheb, Tahereh (57195776188); Sidaoui, Mouwafa...",57195776188; 57202443478; 57556170500,Convergence of artificial intelligence with so...,2024,Telematics and Informatics Reports,14,NaN,100146,NaN,NaN,NaN,2,10.1016/j.teler.2024.100146,https://www.scopus.com/inward/record.uri?eid=2...,Review,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85192863692
2,Alsuwat E.; Alsuwat H.,"Alsuwat, Emad (57207994539); Alsuwat, Hatim (5...",57207994539; 57208004414,An improved multi-modal framework for fake new...,2025,Journal of Supercomputing,81,1,177,NaN,NaN,NaN,0,10.1007/s11227-024-06671-z,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-85209090030
3,Trajano D.; Bordini R.H.; Vieira R.,"Trajano, Douglas (57387425500); Bordini, Rafae...",57387425500; 57203102955; 7103235792,OLID-BR: offensive language identification dat...,2024,Language Resources and Evaluation,58,4,NaN,1263.0,1289.0,26.0,2,10.1007/s10579-023-09657-0,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85158163506
4,Raja E.; Soni B.; Borgohain S.K.,"Raja, Eduri (58525267900); Soni, Badal (571400...",58525267900; 57140022100; 22333249500,Fake news detection in Dravidian languages usi...,2024,Expert Systems with Applications,250,NaN,123967,NaN,NaN,NaN,0,10.1016/j.eswa.2024.123967,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-85190273274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,Chen Y.; Conroy N.J.; Rubin V.L.,"Chen, Yimin (36660670500); Conroy, Niall J. (5...",36660670500; 55756038300; 35724638200,News in an online world: The need for an “auto...,2015,Proceedings of the Association for Information...,52,1,NaN,1.0,4.0,3.0,81,10.1002/pra2.2015.145052010081,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-84987711761
1607,Qazvinian V.; Rosengren E.; Radev D.R.; Mei Q.,"Qazvinian, Vahed (26325744500); Rosengren, Emi...",26325744500; 37104791100; 7006578526; 12241600600,Rumor has it: Identifying misinformation in mi...,2011,EMNLP 2011 - Conference on Empirical Methods i...,NaN,NaN,NaN,1589.0,1599.0,10.0,735,NaN,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-80053291127
1608,Dunn E.J.; Moga P.J.,"Dunn, Edward J. (56430566600); Moga, Paul J. (...",56430566600; 6506991238,Patient misidentification in laboratory medici...,2010,Archives of Pathology and Laboratory Medicine,134,2,NaN,244.0,255.0,11.0,67,NaN,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-76449100520
1609,Singhania S.; Fernandez N.; Rao S.,"Singhania, Sneha (58655886000); Fernandez, Nig...",58655886000; 58714600900; 57206243517,3HAN: A Deep Neural Network for Fake News Dete...,2017,Lecture Notes in Computer Science (including s...,10635 LNCS,NaN,NaN,572.0,581.0,9.0,93,10.1007/978-3-319-70096-0_59,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-85035092969
1610,Pisarevskaya D.,"Pisarevskaya, D. (57194718044)",57194718044,Rhetorical structure theory as a feature for d...,2017,Komp'juternaja Lingvistika i Intellektual'nye ...,1,16,NaN,191.0,200.0,9.0,6,NaN,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-85021806697

In [ ]:
citation_counts = []

for title in df["Title"]:
    try:
        result = cr.works(query=title)
        if "message" in result and "items" in result["message"] and len(result["message"]["items"]) > 0:
            citations = result["message"]["items"][0].get("is-referenced-by-count", 0)
            citation_counts.append(citations)
            print(f"Citations for {title}: {citations}")
        else:
            citation_counts.append(None)
    except Exception as e:
        citation_counts.append(None)
        print(f"Error fetching {title}: {e}")

# Add citation data to DataFrame
df["Citations"] = citation_counts

# Save results
df.to_csv("articles_with_citations_scopus.csv", index=False)

print("Citation data saved successfully!")

Citations for Distinguishing Human Journalists from Artificial Storytellers Through Stylistic Fingerprints: 0
Citations for Convergence of artificial intelligence with social media: A bibliometric & qualitative analysis: 0
Citations for An improved multi-modal framework for fake news detection using NLP and Bi-LSTM: 0
Citations for OLID-BR: offensive language identification dataset for Brazilian Portuguese: 0
Citations for Fake news detection in Dravidian languages using multiscale residual CNN_BiLSTM hybrid model: 0
Citations for Linguistic feature fusion for Arabic fake news detection and named entity recognition using reinforcement learning and swarm optimization: 0
Citations for “The ChatGPT bot is causing panic now – but it’ll soon be as mundane a tool as Excel”: analysing topics, sentiment and emotions relating to ChatGPT on Twitter: 1
Citations for Cross-modal augmentation for few-shot multimodal fake news detection: 0
Citations for TinyLLM Efficacy in Low-Resource Language: An Experiment on Bangla Text Classification Task: 0
Citations for Unmasking Fake News: Navigating the Landscape of Fake News Identification, Challenges and Issues: 0
Citations for A comprehensive overview of fake news detection on social networks: 1
Citations for Detecting fake news for COVID-19 using deep learning: a review: 2
Citations for Evaluation of an LLM in Identifying Logical Fallacies: A Call for Rigor When Adopting LLMs in HCI Research: 0
Citations for Building a framework for fake news detection in the health domain: 0
Citations for Machine Learning for Predicting Key Factors to Identify Misinformation in Football Transfer News: 2
Citations for What makes sentiment signals work? Sentiment and stance multi-task learning for fake news detection: 0
Citations for Two-Way Truth Seeker: A Hybrid Method Using LSTM and BiLSTM to Recognize and Classify Fake News: 0
Citations for An Interactive Web Application Utilizing Machine Learning Techniques to Identify and Flag Fabricated News Articles: 0
Citations for Fake news detection in low-resource languages: A novel hybrid summarization approach: 1
Citations for Evaluating text classification: A benchmark study: 1
Citations for Human Versus Machine Intelligence: Assessing Natural Language Generation Models Through Complex Systems Theory: 2
Citations for OASIS 2024 - Proceedings of the 2024 Workshop on Open Challenges in Online Social Media, Held in conjunction with the 35th ACM Conference on Hypertext and Social Media, HT 2024: 0
Citations for Fake News Detection System, based on CBOW and BERT: 0
Citations for A Predictive Model for Benchmarking the Performance of Algorithms for Fake and Counterfeit News Classification in Global Networks: 0
Citations for Automated Detection of Misinformation: A Hybrid Approach for Fake News Detection: 0
Citations for Sentiment score-based classification for fake news using machine learning and LSTM-BiLSTM: 0
Citations for A Survey on the Use of Large Language Models (LLMs) in Fake News: 0
Citations for Toward the Adoption of Explainable Pre-Trained Large Language Models for Classifying Human-Written and AI-Generated Sentences: 0
Citations for Advances in edge-cloud collaboration and evolution for large-small models; [大小模型端云协同进化技术进展]: 0
Citations for Novel approach for Arabic fake news classification using embedding from large language features with CNN-LSTM ensemble model and explainable AI: 0
Citations for Ensemble Techniques for Robust Fake News Detection: Integrating Transformers, Natural Language Processing, and Machine Learning: 0
Citations for Effective Fake News Classification Based on Lightweight RNN with NLP: 0
Citations for Disinformation, Fakes and Propaganda Identifying Methods in Online Messages Based on NLP and Machine Learning Methods: 0
Citations for A metaheuristic based filter-wrapper approach to feature selection for fake news detection: 0
Citations for Explainable Deep Learning for False Information Identification: An Argumentation Theory Approach: 1
Citations for Federated Learning in the Detection of Fake News Using Deep Learning as a Basic Method: 4
Citations for Transformer-based models for combating rumours on microblogging platforms: a review: 0
Citations for 3rd International Conference on Trends in Electronics and Health Informatics, TEHI 2023: 0
Citations for Exposing and explaining fake news on-the-fly: 0
Citations for LLaMA 3 vs. State-of-the-Art Large Language Models: Performance in Detecting Nuanced Fake News: 0
Citations for Enhancing COVID-19 misinformation detection through novel attention mechanisms in NLP: 0
Citations for Towards Optimal NLP Solutions: Analyzing GPT and LLaMA-2 Models Across Model Scale, Dataset Size, and Task Diversity: 2
Citations for Towards explainable fake news detection and automated content credibility assessment: Polish internet and digital media use-case: 0
Citations for Explore the Style for Fake News Detection: 0
Citations for Transformer-Based Quantification of the Echo Chamber Effect in Online Communities: 0
Citations for Machine learning-based detection of fake news in Afan Oromo language: 0
Citations for 360 Degrees rumor detection: When explanations got some explaining to do: 5
Citations for Chemical, biological, radiological and nuclear event detection and classification using ontology interrogation and social media data: 0
Citations for Large Language Model Agentic Approach to Fact Checking and Fake News Detection: 0
Citations for RT-NIG: Reconstructing Two-tuples in Neighborhood Information Graphs for Early Rumor Detection; [RT-NIG: 在邻域信息图中重构二元组用于谣言早期检测]: 0
Citations for Performance analysis of semantic veracity enhance (SVE) classifier for fake news detection and demystifying the online user behaviour in social media using sentiment analysis: 0
Citations for Fake news detection: recent trends and challenges: 0
Citations for Fake news prediction in social media using natural language processing technique compared to Bayesian networks with classified accuracy: 0
Citations for AraCovTexFinder: Leveraging the transformer-based language model for Arabic COVID-19 text identification: 2
Citations for Detecting Misinformation in COVID-19 Content: A Machine Learning and Deep Learning Approach with Word Embeddings: 0
Citations for Enhancing Fake News Detection with Word Embedding: A Machine Learning and Deep Learning Approach: 0
Citations for Domain Independent Deception Detection: Feature Sets, LIWC Efficacy, and Synthetic Data Challenges: 0
Citations for Enhancing Arabic Fake News Detection: Evaluating Data Balancing Techniques Across Multiple Machine Learning Models: 0
Citations for A Comparative Study of Hybrid Models in Health Misinformation Text Classification: 0
Citations for DRIVE: An adjustable parallel architecture based on evidence awareness for fake news detection: 0
Citations for A novel integration of multiple learning methods for detecting misleading information from different datasets during the pandemic: 0
Citations for Is checkworthiness generalizable? Evaluating task and domain generalization of datasets for claim detection: 0
Citations for Text pre-processing techniques in addressing fake news: 0
Citations for Critical Climate Machine: A Visual and Musical Exploration of Climate Misinformation through Machine Learning: 0
Citations for The Comparison of Deep Learning Models for Indonesian Political Hoax News Detection: 0
Citations for Modality Deep-learning Frameworks for Fake News Detection on Social Networks: A Systematic Literature Review: 0
Citations for A regularization based simple shallow perceptron network for detection of fake news in social networks: 0
Citations for A knowledge-Aware NLP-Driven conversational model to detect deceptive contents on social media posts: 0
Citations for Fake-news detection: a survey of evaluation Arabic datasets: 0
Citations for Adaptive weighted feature fusion for multiscale atrous convolution-based 1DCNN with dilated LSTM-aided fake news detection using regional language text information: 0
Citations for Measuring Epistemic Trust: Towards a New Lens for Democratic Legitimacy, Misinformation, and Echo Chambers: 0
Citations for Arabic Fake News Detection in Social Media Context Using Word Embeddings and Pre-trained Transformers: 1
Citations for Cognitive biases in natural language: Automatically detecting, differentiating, and measuring bias in text: 0
Citations for FMC: Multimodal fake news detection based on multi-granularity feature fusion and contrastive learning: 0
Citations for Natural language processing for fake news detection using hybrid deep learning techniques: 0
Citations for Novel approach for predicting fake news stance detection using large word embedding blending and customized CNN model: 0
Citations for Cross-Domain Fake News Detection Using a Prompt-Based Approach: 0
Citations for ICPR 2024 Competition on Multilingual Claim-Span Identification: 0
Citations for GBERT: A hybrid deep learning model based on GPT-BERT for fake news detection: 1
Citations for Analyzing common lexical features of fake news using multi-head attention weights: 0
Citations for A Hybrid Ensemble Learning Approach for Detecting Bots on Twitter: 0
Citations for Enhancing authenticity and trust in social media: an automated approach for detecting fake profiles: 1
Citations for Boosting generalization of fine-tuning BERT for fake news detection: 2
Citations for Backtranslate what you are saying and I will tell who you are: 1
Citations for MIS’24: 1st ACM Multimedia Workshop on Multi-modal Misinformation Governance in the Era of Foundation Models: 0
Citations for Pre-Trained Language Model Ensemble for Arabic Fake News Detection: 0
Citations for Unmasking offensive content: a multimodal approach with emotional understanding: 0
Citations for Enhancing Arabic fake news detection with a hybrid MLP-SVM approach and Doc2Vec embeddings: 0
Citations for Did You Tell a Deadly Lie? Evaluating Large Language Models for Health Misinformation Identification: 0
Citations for Social media's dark secrets: A propagation, lexical and psycholinguistic oriented deep learning approach for fake news proliferation: 0
Citations for Exploiting Content Characteristics for Explainable Detection of Fake News: 1
Citations for Investigating Characteristics, Biases and Evolution of Fact-Checked Claims on the Web: 0
Citations for A Survey of Text Classification Algorithms and Application Scenarios; [文本分类算法及其应用场景研究综述]: 0
Citations for Fake News Detection Revisited: An Extensive Review of Theoretical Frameworks, Dataset Assessments, Model Constraints, and Forward-Looking Research Agendas: 0
Citations for Text–image multimodal fusion model for enhanced fake news detection: 0
Citations for A Deep Learning Multimodal Framework for Fake News Detection: 0
Citations for Early detection of fake news on emerging topics through weak supervision: 1
Citations for Fake News Detection Using Recurrent Neural Network in Somali Language: 0
Citations for Propositional claim detection: a task and dataset for the classification of claims to truth: 0
Citations for Survey of machine learning techniques for Arabic fake news detection: 1
Citations for Large language models in food science: Innovations, applications, and future: 0
Citations for The Art of Deepfake Text Obfuscation: Lessons Learned From a Manual, First-Person Perspective: 0
Citations for Fake News Detection Using Passive Aggressive Classifier (PAC) & Neural Network: A Hybrid Approach: 0
Citations for AI Knows You: Deep Learning Model for Prediction of Extroversion Personality Trait: 0
Citations for Dataset for multimodal fake news detection and verification tasks: 0
Citations for Boosting Fake News Detection Accuracy: A Deep Dive into LSTM Classifiers: 0
Citations for Mapping automatic social media information disorder. The role of bots and AI in spreading misleading information in society: 5
Citations for Detecting Fake News on Social Networks: A Naive Bayes Approach to Enhance Information Trustworthiness: 0
Citations for Social Media Fake News Detection Using Machine Learning Models and Feature Extraction Techniques: 0
Citations for Graph global attention network with memory: A deep learning approach for fake news detection: 4
Citations for Multimodal Emotion Recognition in the Political Domain in Spanish: 0
Citations for Fake News Detection Approach Using Hybrid Deep Learning Framework: 0
Citations for LSTMCNN: A hybrid machine learning model to unmask fake news: 0
Citations for Classifying True and Fake News Using LSTM Architecture: 0
Citations for Interpretable AI Insights in Fake News Detection: A Comparative Analysis of CNN and LSTM: 0
Citations for Fake News Detection Using Machine Learning Algorithms: 0
Citations for Deep Learning Analysis for Revealing Fake News using Linguistic Complexity and Semantic Signatures.: 1
Citations for A fusion of BERT, machine learning and manual approach for fake news detection: 2
Citations for Fake News Classification: A Linguistic Feature Selection Approach to Handle Imbalanced Data in Spanish: 0
Citations for Leveraging Advanced Prompting Strategies in Llama-8b for Enhanced Hyperpartisan News Detection: 11
Citations for Russo-Ukrainian war disinformation detection in suspicious Telegram channels: 0
Citations for A Comprehensive Survey on Automatic Detection of Fake News Using Natural Language Processing: Challenges and Limitations: 0
Citations for Detecting Evolving Fake News in Social Media by Leveraging Heterogeneous Deep Learning Model: 0
Citations for Investigating Appraisal and the Language of Evaluation in Fake News Corpora: 0
Citations for A framework for detecting fake news by identifying fake text messages and forgery images: 0
Citations for Identifying Inaccurate Stories: Leveraging High Knowledge and Big Data: 0
Citations for A Novel Temporal Footprints-Based Framework for Fake News Detection: 0
Citations for Exploring the Relationship between News Reliability and Violent Comments in Digital Media: 181
Citations for When explainability turns into a threat - using xAI to fool a fake news detection method: 7
Citations for An Attribute-wise Attention model with BiLSTM for an efficient Fake News Detection: 1
Citations for A Hybrid DistilBERT-BiGRU Model for Enhanced Misinformation Detection: Leveraging Transformer-Based Pretraining Language Model: 0
Citations for A Comparative Study in Large Language Models Usage for Fake News Detection: 0
Citations for A fundamental overview of ensemble deep learning models and applications: systematic literature and state of the art: 0
Citations for Reliable social media framework: fake news detection using modified feature attention based CNN-BiLSTM: 0
Citations for Abstract: 0
Citations for Special issue on infodemics: 0
Citations for Multimodal Fake News Analysis Based on Image-Text Similarity: 6
Citations for Detection of AI Generated Text With BERT Model: 0
Citations for Fake News Detection Using Machine Learning and Deep Learning: 0
Citations for Detecting Fraudulent Reviews in E-commerce Platforms: 0
Citations for Mitigating adversarial manipulation in LLMs: a prompt-based approach to counter Jailbreak attacks (Prompt-G): 0
Citations for Fake news detection: Taxonomy and comparative study: 0
Citations for I-S 2 FND: a novel interpretable self-ensembled semi-supervised model based on transformers for fake news detection: 1
Citations for NLP-DS 2024 - Proceedings of the Doctoral Symposium on Natural Language Processing, held as part of the 40th Edition of the International Conference of the Spanish Society for Natural Language Processing, SEPLN 2024: 0
Citations for Analysing Linguistic Markers on Fake News to Enhance the Explainability of Deception Detection Systems: 2
Citations for Arabic Fake News Detection Using Machine Learning Approach: 0
Citations for Detecting health misinformation: A comparative analysis of machine learning and graph convolutional networks in classification tasks: 0
Citations for Enhancing Model Performance through Translation-based Data Augmentation in the context of Fake News Detection: 0
Citations for Fake News Detection Using Machine Learning and Natural Language Processing: 0
Citations for A Novel Framework for Fake News Detection Using LDA and QDA: 0
Citations for Fake news detection using dual BERT deep neural networks: 6
Citations for Breaking the Fake News Barrier: Deep Learning Approaches in Bangla Language: 0
Citations for Involving Society to Protect Society from Fake News and Disinformation: Crowd sourced Datasets and Text Reliability Assessment: 0
Citations for Model Attribution in LLM-Generated Disinformation: A Domain Generalization Approach with Supervised Contrastive Learning: 0
Citations for A Hybrid Deep Learning Approach for Spam Detection in Twitter: 0
Citations for Fake News Classification Methodology With Enhanced BERT: 0
Citations for RUN-AS: a novel approach to annotate news reliability for disinformation detection: 0
Citations for A novel approach for rumor detection in social platforms: Memory-augmented transformer with graph convolutional networks: 2
Citations for Fake News Detection Incorporating Emotion Transition in Text: 0
Citations for Multilingual Misinformation Detection: Deep Learning Approaches for News Authenticity Assessment: 0
Citations for Fake News Detection Using Feature Extraction, Natural Language Processing, Curriculum Learning, and Deep Learning: 3
Citations for Is text preprocessing still worth the time? A comparative survey on the influence of popular preprocessing methods on Transformers and traditional classifiers: 6
Citations for Explainable Fake News Detection Based on BERT and SHAP Applied to COVID-19: 1
Citations for SEPLN-P 2024 - Poster Proceedings of the 40th Annual Conference of the Spanish Association for Natural Language Processing 2024, co-located with the 40th International Conference of the Spanish Society for Natural Language Processing, SEPLN 2024: 0
Citations for Enhancing Cheapfake Detection: An Approach Using Prompt Engineering and Interleaved Text-Image Model: 1
Citations for Machine Learning Techniques to Detect A Fake News In An Articles: 0
Citations for Improving Bangla Linguistics: Advanced LSTM, Bi-LSTM, and Seq2Seq Models for Translating Sylheti to Modern Bangla: 0
Citations for A Deep Learning Methodology-Based Unsupervised Misinformation Detection (Umd) Technique for Identifying Fabricated Narratives: 0
Citations for Extracting Features from Text Flows based on Semantic Similarity for Text Classification: an Approach Inspired by Audio Analysis: 0
Citations for ENSEMBLE CLASSIFIER BASED FAKE NEWS IDENTIFICATION IN ONLINE SOCIAL NETWORK: 0
Citations for To Click it or not to Click it: An Italian Dataset for Neutralising Clickbait Headlines: 11
Citations for Identification of Fake Information from Internet Propaganda using Deep Learning: 0
Citations for Enhancing hierarchical attention networks with CNN and stylistic features for fake news detection: 0
Citations for Robust multi-domain descriptive text classification leveraging conventional and hybrid deep learning models: 3
Citations for Detecting Out-of-Context Media with LLaMa-Adapter V2 and RoBERTa: An Effective Method for Cheapfakes Detection: 1
Citations for Natural Language Processing Approach for Fake News Detection Using Metaheuristics Optimized Extreme Gradient Boosting: 0
Citations for Exploring COVID-related relationship extraction: Contrasting data sources and analyzing misinformation: 1
Citations for A malicious news detection on social networks using natural language processing technique in comparison with deep learning algorithm with improved F1 score: 0
Citations for Quantifying the impact of misinformation and vaccine-skeptical content on Facebook: 3
Citations for Covid based question criticality prediction with domain adaptive BERT embeddings: 1

# data cleaning

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving iee articles.xlsx to iee articles.xlsx

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving google scholar articles.xlsx to google scholar articles.xlsx

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving scoupus articles.xlsx to scoupus articles.xlsx

In [ ]:
df_scopus = pd.read_excel("scoupus articles.xlsx")
df_iee = pd.read_excel("iee articles.xlsx")
df_goscho = pd.read_excel("google scholar articles.xlsx")

In [ ]:
# Remplacer NaN dans "Author Keywords" par "Index Keywords"
df_scopus["Author Keywords"].fillna(df_scopus["Index Keywords"], inplace=True)

<ipython-input-50-3983845938b7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_scopus["Author Keywords"].fillna(df_scopus["Index Keywords"], inplace=True)

In [ ]:
# Drop the "Index Keywords" column
df_scopus.drop(columns=["Index Keywords"], inplace=True)

In [ ]:
df_iee.drop(columns=["Key"], inplace=True)

In [ ]:
df_goscho.drop(columns=["Key"], inplace=True)

In [ ]:
df_iee.drop(columns=["Publication Title"], inplace=True)

In [ ]:
# Standardize column names
column_mapping = {
    "Authors": "Authors",
    "Author": "Authors",
    "Title": "Title",
    "Year": "Year",
    "Sourcetitle": "Conference Name",
    "Source title": "Conference Name",
    "Publication Title": "Conference Name",
    "Conference Name": "Conference Name",
    "Publication Year": "Year",
    "Cited by": "Citations",
    "Citations": "Citations",
    "DOI": "DOI",
    "Affiliations": "Affiliations",
    "Abstract": "Abstract",
    "Abstract Note": "Abstract",
    "Author Keywords": "Keywords",
    "Automatic Tags": "Keywords",
    "Library Catalog": "Source",
    "Source": "Source",
    "Item Type": "Document Type"
    }

In [ ]:
# Rename columns in each dataset
df_scopus = df_scopus.rename(columns=column_mapping)
df_iee = df_iee.rename(columns=column_mapping)
df_goscho = df_goscho.rename(columns=column_mapping)

In [ ]:
# Define the desired column order
desired_order = ['Document Type', 'Year', 'Authors', 'Title',
                 'Conference Name', 'DOI', 'Abstract', 'Source',
                 'Citations', 'Keywords']

# Reorder the DataFrame columns
df_iee = df_iee[desired_order]

In [ ]:
df_iee

,Document Type,Year,Authors,Title,Conference Name,DOI,Abstract,Source,Citations,Keywords
0,conferencePaper,2024.0,"Vadakkethil Somanathan Pillai, Sanjaikanth E; ...",Leveraging Natural Language Processing for Det...,2024 2nd International Conference on Disruptiv...,10.1109/ICDT61202.2024.10489386,Fake news have become a number one situation w...,IEEE Xplore,0,Data models; Decision making; Disruptive techn...
1,conferencePaper,2022.0,"Matheven, Anand; Kumar, Burra Venkata Durga",Fake News Detection Using Deep Learning and Na...,2022 9th International Conference on Soft Comp...,10.1109/ISCMI56532.2022.10068440,The rise of social media has brought the rise ...,IEEE Xplore,6,Fake news; Natural language processing; Social...
2,conferencePaper,2024.0,"Nirmala, M; Navya, R",Machine Learning Techniques to Detect A Fake N...,2024 Second International Conference on Networ...,10.1109/NMITCON62075.2024.10699063,The rampant spread of misinformation undermine...,IEEE Xplore,0,Fake news; Natural language processing; Deep l...
3,conferencePaper,2023.0,"Misra, Shamik; Tandon, Prabhat; Panda, Purna C...",Optimization of Hugging Face Transformers for ...,"2023 International Conference on Data Science,...",10.1109/ICDSAAI59313.2023.10452606,"The upsurge of fake news in recent times, faci...",IEEE Xplore,0,Fake news; Fake News Detection; Adaptation mod...
4,conferencePaper,2023.0,"Rakib Mollah, Md. Abdur; Kabir, Mir Md. Jahang...",Detection of Fake News with RoBERTa Based Embe...,2023 26th International Conference on Computer...,10.1109/ICCIT60459.2023.10441206,The spread of fake news has emerged as a criti...,IEEE Xplore,0,Fake news; Transformers; Artificial neural net...
...,...,...,...,...,...,...,...,...,...,...
665,journalArticle,2024.0,"Ruan, Qin; Mac Namee, Brian; Dong, Ruihai",The Effects of Media Bias on News Recommendations,NaN,10.1109/ACCESS.2024.3413772,"The negative effects of media bias, such as in...",IEEE Xplore,0,Fake news; Task analysis; Neural networks; Med...
666,conferencePaper,2023.0,"Misini, Arta; Kadriu, Arbana; Canhasi, Ercan",Albanian Authorship Attribution Model,2023 12th Mediterranean Conference on Embedded...,10.1109/MECO58584.2023.10155046,Authorship attribution (AA) is a subfield of N...,IEEE Xplore,1,Machine learning; Support vector machines; Nat...
667,journalArticle,2020.0,"Kausar, Soufia; Tahir, Bilal; Mehmood, Muhamma...",ProSOUL: A Framework to Identify Propaganda Fr...,NaN,10.1109/ACCESS.2020.3028131,"Today, the rapid dissemination of information ...",IEEE Xplore,24,Feature extraction; Linguistics; Dictionaries;...
668,conferencePaper,2023.0,"Pal, Satinder; Lamba, Anil Kumar",Tweeting Truth: Investigating False Informatio...,2023 IEEE World Conference on Applied Intellig...,10.1109/AIC57670.2023.10263951,The emergence of social media platforms has re...,IEEE Xplore,1,Machine Learning; Social networking (online); ...
669,conferencePaper,2024.0,"Chauhan, Shubham; Verma, Shija; Pandey, Ayushi...",Media Bias Monitor: Quantifying Biases of Indi...,2024 15th International Conference on Computin...,10.1109/ICCCNT61001.2024.10724364,"Throughout history, mass media has significant...",IEEE Xplore,0,Fake news; NLP; Text categorization; Sentiment...

In [ ]:
df_goscho

,Document Type,Year,Authors,Title,Conference Name,DOI,Abstract,Source,Citations
0,journalArticle,2021.0,"Bangyal, Waqas Haider; Qasim, Rukhma; Rehman, ...",Detection of Fake News Text Classification on ...,Computational and Mathematical Methods in Medi...,10.1155/2021/5514220,A vast amount of data is generated every secon...,DOI.org (Crossref),68
1,preprint,2022.0,"Ahmed, Sajjad; Hinkelmann, Knut; Corradini, Fl...",Development of Fake News Model using Machine L...,NaN,10.48550/arXiv.2201.07489,Fake news detection research is still in the e...,arXiv.org,0
2,journalArticle,2020.0,"Su, Qi; Wan, Mingyu; Liu, Xiaoqian; Huang, Chu...","Motivations, methods and metrics of misinforma...",Natural Language Processing Research,NaN,NaN,Google Scholar,35
3,journalArticle,2022.0,"Prachi, Noshin Nirvana; Habibullah, Md; Rafi, ...",Detection of Fake News Using Machine Learning ...,Journal of Advances in Information Technology,NaN,NaN,Google Scholar,0
4,journalArticle,2021.0,"de Oliveira, Nicollas R.; Pisa, Pedro S.; Lope...",Identifying fake news on social networks based...,Information,NaN,NaN,Google Scholar,0
...,...,...,...,...,...,...,...,...,...
936,conferencePaper,2021.0,"Kaliyar, Rohit Kumar; Fitwe, Kedar; Rajarajesw...",Classification of Hoax/Non-Hoax news articles ...,2021 5th International Conference on Computing...,NaN,NaN,Google Scholar,7
937,journalArticle,2021.0,"Paschalides, Demetris; Christodoulou, Chrysova...",Check-It: A plugin for detecting fake news on ...,Online Social Networks and Media,NaN,NaN,Google Scholar,15
938,bookSection,2023.0,"Mirnalinee, T. T.; Jayaraman, Bhuvana; Anirudh...",A Novel Dataset for Fake News Detection in Tam...,Speech and Language Technologies for Low-Resou...,NaN,NaN,DOI.org (Crossref),1
939,document,2023.0,"Mengoni, Paolo; Santucci, Valentino",Special Issue â€œRecent Trends in Natural Lang...,NaN,NaN,NaN,Google Scholar,1
940,bookSection,2021.0,"Selva Birunda, S.; Kanniga Devi, R.",A Review on Word Embedding Techniques for Text...,Innovative Data Communication Technologies and...,NaN,NaN,DOI.org (Crossref),0

In [ ]:
# Define the desired column order
desired_order = ['Document Type', 'Year', 'Authors', 'Title',
                 'Conference Name', 'DOI', 'Abstract', 'Source',
                 'Citations', 'Keywords','Affiliations']

# Reorder the DataFrame columns
df_scopus = df_scopus[desired_order]

In [ ]:
# Merge the datasets using an outer join
df_merged = pd.concat([df_iee, df_goscho, df_scopus], ignore_index=True, sort=False)

In [ ]:
# Remove rows where "Author" is missing
df_merged = df_merged.dropna(subset=["Authors"])

In [ ]:
df_merged = df_merged.dropna(subset=["Conference Name"])

In [ ]:
df_merged = df_merged.dropna(subset=["Abstract"])

In [ ]:
df_merged = df_merged.dropna(subset=["DOI"])

In [ ]:
df_merged['Year'] = df_merged['Year'].astype('Int64')

In [ ]:
unique_sources_list = df_merged['Document Type'].dropna().unique().tolist()
print(unique_sources_list)

['conferencePaper', 'journalArticle', 'Article', 'Conference paper', 'Review', 'Book chapter', 'Data paper', 'Editorial', 'Book', 'Note', 'Retracted']

In [ ]:
unique_sources_list = df_merged['Source'].dropna().unique().tolist()
print(unique_sources_list)

['IEEE Xplore', 'DOI.org (Crossref)', 'arXiv.org', 'Scopus']

In [ ]:
#df_merged = df_merged[df_merged['Citations'] != 0]  # Supprimer les zéros
#df_merged = df_merged.reset_index(drop=True)  # Réinitialiser l'index

In [ ]:
# Count occurrences of each unique value in the 'Citations' column
citations_counts = df_merged['Citations'].value_counts()

# Display the result
print(citations_counts)

Citations
0      656
1      254
2      176
3      135
4       89
      ...
184      1
414      1
97       1
250      1
479      1
Name: count, Length: 106, dtype: int64

In [ ]:
df_merged

,Document Type,Year,Authors,Title,Conference Name,DOI,Abstract,Source,Citations,Keywords,Affiliations
0,conferencePaper,2024,"Vadakkethil Somanathan Pillai, Sanjaikanth E; ...",Leveraging Natural Language Processing for Det...,2024 2nd International Conference on Disruptiv...,10.1109/ICDT61202.2024.10489386,Fake news have become a number one situation w...,IEEE Xplore,0,Data models; Decision making; Disruptive techn...,NaN
1,conferencePaper,2022,"Matheven, Anand; Kumar, Burra Venkata Durga",Fake News Detection Using Deep Learning and Na...,2022 9th International Conference on Soft Comp...,10.1109/ISCMI56532.2022.10068440,The rise of social media has brought the rise ...,IEEE Xplore,6,Fake news; Natural language processing; Social...,NaN
2,conferencePaper,2024,"Nirmala, M; Navya, R",Machine Learning Techniques to Detect A Fake N...,2024 Second International Conference on Networ...,10.1109/NMITCON62075.2024.10699063,The rampant spread of misinformation undermine...,IEEE Xplore,0,Fake news; Natural language processing; Deep l...,NaN
3,conferencePaper,2023,"Misra, Shamik; Tandon, Prabhat; Panda, Purna C...",Optimization of Hugging Face Transformers for ...,"2023 International Conference on Data Science,...",10.1109/ICDSAAI59313.2023.10452606,"The upsurge of fake news in recent times, faci...",IEEE Xplore,0,Fake news; Fake News Detection; Adaptation mod...,NaN
4,conferencePaper,2023,"Rakib Mollah, Md. Abdur; Kabir, Mir Md. Jahang...",Detection of Fake News with RoBERTa Based Embe...,2023 26th International Conference on Computer...,10.1109/ICCIT60459.2023.10441206,The spread of fake news has emerged as a criti...,IEEE Xplore,0,Fake news; Transformers; Artificial neural net...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3206,Article,2015,Chen Y.; Conroy N.J.; Rubin V.L.,News in an online world: The need for an “auto...,Proceedings of the Association for Information...,10.1002/pra2.2015.145052010081,Widespread adoption of internet technologies h...,Scopus,81,credibility assessment; deception detection; f...,Language and Information Technology Research L...
3209,Conference paper,2017,Pisarevskaya D.,Deception detection in news reports in the rus...,EMNLP 2017 - 2nd Workshop on Natural Language ...,10.18653/v1/w17-4213,Different language markers can be used to reve...,Scopus,22,Classification (of information); Decision tree...,NaN
3210,Conference paper,2017,Ahmed H.; Traore I.; Saad S.,Detection of Online Fake News Using N-Gram Ana...,Lecture Notes in Computer Science (including s...,10.1007/978-3-319-69155-8_9,Fake news is a phenomenon which is having a si...,Scopus,479,Fake news detection; N-gram analysis; Online f...,"ECE Department, University of Victoria, Victor..."
3211,Conference paper,2018,Agudelo G.E.R.; Parra O.J.S.; Velandia J.B.,Raising a model for fake news detection using ...,Lecture Notes in Computer Science (including s...,10.1007/978-3-030-02131-3_52,Fake news has been spreading in greater number...,Scopus,13,Fake news; Machine learning; NLTK; Sklearn,"Faculty of Engineering, Universidad Distrital ..."
3215,Conference paper,2017,Aker A.; Derczynski L.; Bontcheva K.,Simple open stance classification for rumour a...,International Conference Recent Advances in Na...,10.26615/978-954-452-049-6_005,"Stance classification determines the attitude,...",Scopus,41,Deep learning; Extraction; Fake detection; Nat...,"Department of Computer Science, University of ..."

In [ ]:
df_merged.to_csv("articles_merged.csv", index=False)